TODO1/how-apple-beat-swiss-watchmakers-at-their-own-game.md
苹果公司如何颠覆瑞士制表业
译文翻译完成，resolve #4563
=> 苹果公司如何颠覆瑞士制表业

TODO1/the-6-most-desirable-coding-jobs-and-the-types-of-people-drawn-to-each.md
=> 6 个最令人满意的和编程相关的工作（和参与这些工作的人们的类型）

TODO1/exploratory-statistical-data-analysis-with-a-kaggle-dataset-using-pandas.md
使用 Pandas 对 Kaggle 数据集进行统计数据分析
译文翻译完成，resolve #4656
=> 使用 Pandas 对 Kaggle 数据集进行统计数据分析

TODO1/extracting-insights-from-a-kaggle-dataset-using-pythons-pandas-and-seaborn.md
使用 Python 的 Pandas 和 Seaborn 框架从 Kaggle 数据集中提取信息
译文翻译完成，resolve #4657
=> 使用 Python 的 Pandas 和 Seaborn 框架从 Kaggle 数据集中提取信息

TODO1/creating-spm-tools-from-your-existing-codebase.md
=> 从现有的代码库创建 Swift 包管理器

TODO1/how-we-made-carousells-mobile-web-experience-3x-faster.md
=> 我们是怎样把 Carousell 的移动端 Web 体验搞快了 3 倍的？

TODO1/graphql-server-design-medium.md
=> Medium 的 GraphQL 服务设计

TODO1/a-guide-to-custom-elements-for-react-developers.md
译文翻译完成，resolve #4767
另改了部分代码的缩进错乱问题
=> 写给 React 开发者的自定义元素指南

TODO1/google-colab-free-gpu-tutorial.md
Google Colab 免费 GPU 使用教程
译文翻译完成，欢迎校对~~~
resolve #4788
=> Google Colab 免费 GPU 使用教程

TODO1/python-libraries-for-data-science-other-than-pandas-and-numpy.md
鲜为人知的数据科学 Python 库
译文翻译完成，欢迎校对~~~
resolve #4772
=> 鲜为人知的数据科学 Python 库

TODO1/building-beautiful-flexible-user-interfaces-with-flutter-material-theming-and-official-material.md
使用 Flutter，Material Theming 和官方材质组件（MDC）构建美观，灵活的用户界面
译文翻译完成，欢迎指正！
resolve #4804
=> 使用 Flutter，Material Theming 和官方材质组件（MDC）构建美观，灵活的用户界面

TODO1/how-does-react-tell-a-class-from-a-function.md, design.md
=> React 是如何区分 Class 和 Function 的 ?

TODO1/mobile-apps-capacitor-vue-js.md
=> 使用Capacitor 和 Vue.js 构建移动应用

TODO1/how-to-react-native-web-app-a-happy-struggle.md
怎么做：React Native 网页应用。 一场开心的挣扎
译文翻译完成，resolve #4781
=> 怎么做：React Native 网页应用，一场开心的挣扎 

TODO1/mdc-101-flutter.md
MDC-101 Flutter：Material Components（MDC）基础（Flutter）
译文翻译完成，resolve #4818 
文章部分区域根据原网页进行排版，请校对的同学重点留意
=> MDC-101 Flutter：Material Components（MDC）基础（Flutter）

TODO1/control-flow-integrity-in-android-kernel.md
@leviding  译文翻译完成，resolve #4713
=> Android 内核控制流完整性

TODO1/protected-routes-and-authentication-with-react-and-node-js.md
用 React 和 Node.js 实现受保护的路由和权限验证
译文翻译完成，resolve #4738
=> 用 React 和 Node.js 实现受保护的路由和权限验证

TODO1/developing-a-single-page-app-with-flask-and-vuejs.md
=> 用 Flask 和 Vue.js 开发一个单页面应用

TODO1/static-properties-in-javascript-with-inheritance.md
继承 JavaScript 类中的静态属性
译文翻译完成，resolve #4861
=> 继承 JavaScript 类中的静态属性

TODO1/supercharging-your-app-development-speed-with-custom-file-templates.md
=> 使用自定义文件模板加快你的应用开发速度

TODO1/how-to-make-a-beautiful-tiny-npm-package-and-publish-it.md
=> 创建并发布一个小而美的 npm 包

TODO1/5-tools-for-faster-development-in-react.md
@leviding 
译文翻译完成，resolve #4879
=> 5 款工具助力 React 快速开发

TODO1/write-once-run-everywhere-tests-on-android.md
Android 上一次编写，到处测试
译文翻译完成，resolve #4906
=> Android 上一次编写，到处测试

TODO1/zero-to-one-with-flutter.md
=> Flutter 从 0 到 1

TODO1/data-visualization-with-bokeh-in-python-part-one-getting-started.md
=> 利用 Python中的 Bokeh 实现数据可视化，第一部分：入门

TODO1/getting-the-most-from-the-new-multi-camera-api.md
充分利用多摄像头 API
译文翻译完成，resolve #4936
=> 充分利用多摄像头 API

TODO1/a-comprehensive-look-back-at-frontend-in-2018.md
@leviding 译文翻译完成，resolve #4958
=> 2018 前端全面回顾

TODO1/asynchronous-tasks-with-flask-and-redis-queue.md
=> 在 Flask 中使用 Redis Queue 实现异步任务

TODO1/lets-talk-js-documentation.md
=> 讨论 JS ⚡：文档

TODO1/mdc-103-flutter.md
MDC-103 Flutter: Material Theming 的颜色、形状、高度和类型（Flutter）
由于学校考试导致翻译延期，十分抱歉。@leviding 
译文翻译完成，resolve #4913
=> MDC-103 Flutter: Material Theming 的颜色、形状、高度和类型（Flutter）

TODO1/dns-over-tls.md
=> DNS over TLS：端到端加密的 DNS

TODO1/using-proxy-to-track-javascript-class.md
=> 使用 Proxy 来观测 Javascript 中的类

TODO1/i-worked-with-a-data-scientist-heres-what-i-learned.md
=> 我作为软件工程师与一名数据科学家合作的经历 #4966

TODO1/5-animation-packages-ionic.md
=> 5 个可以立刻在你的 Ionic App 中用上的动画包

TODO1/courier-dropbox-migration-to-grpc.md
=> Courier: Dropbox 的 gRPC 迁移利器

TODO1/one-year-with-flutter-my-experience.md
我与 Flutter 的一年
译文翻译完成，resolve #5031
=> 我与 Flutter 的一年

TODO1/react-native-bridge-for-ios-and-android.md
=> React Native 与 iOS 和 Android 通信

TODO1/blockchain-platforms-tech-to-watch-in-2019.md
=> 2019 区块链平台与技术展望

TODO1/a-look-at-css-hyphenation-in-2019.md
=> 2019 CSS 新属性“连字符”初探

TODO1/pwa-native-mobile-apps.md
=> PWA 会取代原生移动应用吗？

TODO1/yarn-vs-npm-everything-you-need-to-know.md
=> 关于 Yarn 和 npm 你所需要知道的一切

TODO1/the-android-dev-summit-2018-app-instant-app-takeaways-open-source.md
Android Dev Summit 2018 应用（instant app 的总结 + 开源）
First commit
译文翻译完成，resolve #5117
=> Android Dev Summit 2018 应用（instant app 的总结 + 开源）

TODO1/ten-things-you-didnt-know-about-webpagetest-org.md
resolve #5027 
Sorry for this delayed pr.
=> 十件你不知道的关于 WebPageTest.org 的事

TODO1/http-3-from-root-to-tip.md
=> HTTP/3: 起源

TODO1/styled-components-magic-explained.md
=> 💅 styled-components 背后的魔力

TODO1/a-tale-of-webpack-4-and-how-to-finally-configure-it-in-the-right-way.md
译文翻译完成，resolve #id
之前一个文章，在 merge 以后提的一些小意见。
=> 校对修改 / Webpack 4 的故事以及如何用正确的方式去最终配置它

TODO1/the-smart-ways-to-correct-mistakes-in-git.md
=> 修改 Git 错误的高明方法

TODO1/How I finally got my head around Scoped Slots in Vue.md, TODO1/how-i-finally-got-my-head-around-scoped-slots-in-vue.md
发布翻译任务：前端-How I finally got my head around Scoped Slots in Vue.md
=> Create How I finally got my head around Scoped Slots in Vue.md

TODO1/draw-a-path-rendering-android-vectordrawables.md
绘制路径:  Android 中矢量图渲染
译文翻译完成，resolve #5093
=> 绘制路径：Android 中矢量图渲染

TODO1/what-hooks-mean-for-vue.md
=> Hooks 对 Vue 而言意味着什么

TODO1/using-errors-as-control-flow-in-swift.md
=> 添加 using-errors-as-control-flow-in-swift.md

TODO1/how-to-use-result-in-swift.md
=> How to use Result in Swift 5

TODO1/performance-under-load.md
发布新文章 performance-under-load.md
@leviding
=> performance-under-load

TODO1/The-Android-Lifecycle-cheat-sheet-part-II-Multiple-activities.md
掘金上有第一章的翻译，后几篇质量都不错，就都翻译完了吧。
@leviding
=> Create The Android Lifecycle cheat sheet — part II: Multiple activities

TODO1/writing-a-microservice-in-rust.md
译文翻译完成，resolve #5198 
校对者请注意：diff 中有一些是对代码部分的缩进调整，因为英文 markdown 中代码部分的缩进有问题
=> 用 Rust 写一个微服务

TODO1/lazy-loading-video-based-on-connection-speed.md
=> 网速敏感的视频延迟加载方案

TODO1/tslint-in-2019.md
=> TSLint in 2019

TODO1/javascript-generator-yield-next-async-await.md
译文翻译完成，resolve #5148 
抱歉，让各位久等了 ~
=> Javascript - Generator-Yield/Next 和 Async-Await

TODO1/The-Android-Lifecycle-cheat-sheet-part-II-Multiple-activities.md
=> Android 生命周期备忘录 — 第二部分：多 Activity

TODO1/using-lstms-for-stock-market-predictions-tensorflow.md
=> 用长短期记忆网络预测股票市场（使用 Tensorflow）

TODO1/longest-keyword-sequence.md
新文章 发布 
@leviding 
这个文章本没有标题，我自己添加的
=> longest-keyword-sequence create new article

TODO1/why-i-write-css-in-javascript.md
=> 为什么我用 JavaScript 来编写 CSS

TODO1/making-the-uamp-sample-an-instant-app.md, TODO1/writing-a-web-server-node.md
=> 转化通用安卓音乐播放器为 instant 应用

TODO1/iOS-Responder-Chain-UIResponder-UIEvent-UIControl-and-uses.md
增加翻译文章 iOS-Responder-Chain-UIResponder-UIEvent-UIControl-and-uses.md
=> iOS Responder Chain: UIResponder, UIEvent, UIControl and uses

TODO1/typescript-with-babel-a-beautiful-marriage.md
=> TypeScript 和 Babel：美丽的结合

TODO1/protecting-a-spring-boot-app-with-apache-shiro.md
译文翻译完成，resolve #5268
不好意思，迟了几天
=> 用 Apache Shiro 来强化一个 Spring Boot 应用

TODO1/how-to-build-a-simple-game-in-the-browser-with-phaser-3-and-typescript.md
=> 如何使用 Phaser 3 和 TypeScript 在浏览器中构建一个简单的游戏

TODO1/using-vector-assets-in-android-apps.md
在 Android 应用中使用矢量资源
译文翻译完成，resolve #5325
=> 在 Android 应用中使用矢量资源

TODO1/how-to-use-result-in-swift.md
如何在 Swift 5 中使用 Result
译文翻译完成，resolve #5271
=> 如何在 Swift 5 中使用 Result

TODO1/mdc-104-flutter.md
译文翻译完成，resolve #5216 
@leviding
=> MDC-104 Flutter：Material 高级组件（Flutter）

TODO1/under-the-hood-of-reacts-hooks-system.md
=> 深入 React Hook 系统的原理

TODO1/time-series-of-price-anomaly-detection.md
=> 时间顺序的价格异常检测

TODO1/The-Android-Lifecycle-cheat-sheet-part-III-Fragments.md
=> Android 生命周期备忘录 — 第三部分：Fragments

TODO1/the-anatomy-of-a-frame.md
=> fix the-anatomy-of-a-frame.md

TODO1/swift-5-exclusivity.md
关于那句话的翻译，为了便于理解，句子原文拆分如下：
```
The exclusivity violation occurs because // 后接子句
the modifier closure both // 并列谓语
reads the captured count variable 
and 
is called 
within the scope of the same variable’s modification. // 修饰上面的谓语
```
为了中文习惯，将修饰语提前。
=> fix(swift-5-exclusivity.md): 增加代码高亮、修正重点句翻译

TODO1/redux-tutorial.md
=> 2019 React Redux 完全指南

TODO1/which-deep-learning-framework-is-growing-fastest.md
=> 哪一个深度学习框架增长最迅猛？TensorFlow 还是 PyTorch？

TODO1/data-binding-lessons-learnt.md
=> Data Binding 库使用的经验教训

TODO1/introducing-workmanager.md
=> Workmanager 简介

TODO1/crafting-reusable-html-templates.md, TODO1/cross-stitching-plaid-and-androidx.md
=> Plaid 应用迁移到 AndroidX 的实践经历

TODO1/running-jupyter-notebooks-on-remote-servers.md
如何在远程服务器上运行Jupyter Notebooks
译文翻译完成，resolve #5558
=> 如何在远程服务器上运行 Jupyter Notebooks

TODO1/how-to-build-a-circular-slider-in-flutter.md
=> 用 Flutter 打造一个圆形滑块（Slider）

TODO1/dependency-injection-in-a-multi-module-project.md
=> 依赖注入在多模块工程中的应用

TODO1/how-do-you-figure.md
=> 你认为“figure”怎么用？

TODO1/logistic-regression-on-mnist-with-pytorch.md
=> 使用 PyTorch 在 MNIST 数据集上进行逻辑回归

TODO1/minimize-for-loop-usage-in-python.md
=> 减少 Python 中循环的使用

TODO1/can-machine-learning-model-simple-math-functions.md
机器学习可以建模简单的数学函数吗？
译文翻译完成，resolve #5698
=> 机器学习可以建模简单的数学函数吗？

TODO1/the-absolute-easiest-way-to-debug-node-js-with-vscode.md
=> 使用 VS Code 调试 Node.js 的超简单方法

TODO1/build-a-drag-and-drop-dnd-layout-builder-with-react-and-immutablejs.md
使用 React 和 ImmutableJS 构建一个拖放布局构建器
译文翻译完成，resolve #5680
=> 使用 React 和 ImmutableJS 构建一个拖放布局构建器

TODO1/an-introduction-to-speech-recognition-using-wfsts.md
=> 使用 WFST 进行语音识别

TODO1/commit-messages-guide.md
=> Commit 提交指南

TODO1/room-coroutines.md
译文初翻完成，resolve #5642  @leviding
=> Room 🔗 Coroutines

TODO1/keras-cheat-sheet.md
Keras 速查表：使用 Python 构建神经网络
译文翻译完成，resolve #5735
=> Keras 速查表：使用 Python 构建神经网络

TODO1/workmanager-basics.md
完成翻译 WorkManager 基础入门
译文翻译完成，resolve #5609
=> WorkManager 基础入门

TODO1/password-reset-emails-in-your-react-app-made-easy-with-nodemailer.md
使用 Nodemailer 轻松构建能通过电子邮件的重置密码 React 应用程序
译文翻译完成，resolve #5711
=> 使用 Nodemailer 轻松构建能通过电子邮件的重置密码的 React 应用程序

TODO1/android-studio-project-marble-apply-changes.md
Android Studio Project Marble: Apply Changes
译文翻译完成，resolve #5668 
标题都是专有名词，暂时没有好的译法，觉得也可以不翻，如果有好的译法可以再修改
=> Android Studio Project Marble: Apply Changes

TODO1/es6-and-npm-modules-in-google-apps-script.md
https://github.com/xitu/gold-miner/issues/5749
译文翻译完成，resolve #5749
=> 在 Google Apps 脚本中使用 ES6 和 npm 模块

TODO1/slide-an-image-to-reveal-text-with-css-animations.md
=> 如何用 CSS Animations 实现图片滑动出文字

TODO1/getting-started-with-c-and-android-native-activities.md
译文初翻完成，resolve #5720
@leviding
=> C++ 和 Android 本地 Activity 初探

TODO1/everything-you-need-to-know-about-flutter-page-route-transition.md
=> 关于 Flutter 页面路由过渡动画，你所需要知道的一切

TODO1/time-series-analysis-visualization-forecasting-with-lstm.md
=> 时间序列分析、可视化、和使用 LSTM 预测

TODO1/guide-node-js-logging.md
Node.js 日志记录指南
译文翻译完成，resolve #5838
=> Node.js 日志记录指南

TODO1/easy-coroutines-in-android-viewmodelscope.md
Android中的简易协程: viewModelScope
译文翻译完成，resolve #5718
=> Android中的简易协程：viewModelScope

TODO1/13-javascript-methods-useful-for-dom-manipulation.md
=> 13 种有用的 JavaScript DOM 操作

TODO1/a-deep-dive-into-native-lazy-loading-for-images-and-frames.md
深入理解图片和框架的原生懒加载功能
译文翻译完成，resolve #5873
=> 深入理解图片和框架的原生懒加载功能

TODO1/flutter-layout-cheat-sheet.md
=> Flutter 布局备忘录

TODO1/4-css-filters-for-adjusting-color.md
=> 4 个 CSS 调色滤镜

TODO1/trick-out-your-terminal-in-10-minutes-or-less.md
=> 不到 10 分钟，让你的终端变好看

TODO1/xcode-and-lldb-advanced-debugging-tutorial-part-1.md
=> Xcode 和 LLDB 高级调试教程：第 1 部分

TODO1/learn-git-concepts-not-commands-1.md
Git：透过命令学概念 —— 第一部分
译文翻译完成，resolve #5921
=> Git：透过命令学概念 —— 第一部分

TODO1/understanding-higher-order-components-in-react.md
这个有个小问题，太粗心啦！来自掘金读者的评论，（line: 93）输出应该是 6，不是 9。
（原文估计写错啦
=> Fix understanding-higher-order-components-in-react

TODO1/how-to-perform-object-detection-with-yolov3-in-keras.md
=> 如何在 Keras 中用 YOLOv3 进行对象检测

TODO1/enabling-modern-js-on-npm.md
=> 在 npm 上启用现在 JavaScript

TODO1/the-childrens-illustrated-guide-to-kubernetes.md
=> Kubernetes 儿童插图指南

TODO1/four-ways-to-quantify-synchrony-between-time-series-data.md
=> 时间序列数据间量化同步的四种方法

TODO1/xcode-and-lldb-advanced-debugging-tutorial-part-2.md
=> Xcode 和 LLDB 高级调试教程：第 2 部分

TODO1/locale-changes-and-the-androidviewmodel-antipattern.md
=> 区域设置更改和 AndroidViewModel 反面模式

TODO1/android-emulator-project-marble-improvements.md
Android 模拟器：Project Marble 中的改进
译文翻译完成，resolve #6047
=> Android 模拟器：Project Marble 中的改进

TODO1/android-networking-in-2019-retrofit-with-kotlins-coroutines.md
=> 2019 年的 Android 网络 —— Retrofit 与 Kotlin 协程

TODO1/the-state-of-graphql-by-reddit.md
=> 从 Reddit 讨论中看到的 GraphQL 现状

TODO1/xgboost-algorithm-long-may-she-reign.md
=> XGBoost 算法万岁！

TODO1/subscriptions-101-for-android-apps.md
=> Android 应用程序的订阅 101 系列视频

TODO1/how-does-the-development-mode-work.md
=> 开发模式的工作原理是什么？

TODO1/learning-parser-combinators-with-rust-4.md
* 翻译完后 1/4
译文翻译完成，resolve #6155
=> 通过 Rust 学习解析器组合器 — 第四部分

TODO1/a-little-reminder-that-pseudo-elements-are-children-kinda.md
小提示：伪元素是子元素，吧。
译文翻译完成，resolve #6287
=> 小提示：伪元素是子元素，吧。

TODO1/http-security-headers-a-complete-guide.md
HTTP Security Headers 完整指南
译文翻译完成，resolve #6283
=> HTTP Security Headers 完整指南

TODO1/learn-enough-docker-to-be-useful-1.md
=> Docker 的学习和应用

TODO1/react-16-lifecycle-methods-how-and-when-to-use-them.md
=> React 16 生命周期函数：如何以及何时使用它们

TODO1/checking-the-network-connection-with-a-react-hook.md
=> 使用 React Hook 来检查网络连接状态

TODO1/what-replaces-javascript.md
有些地方翻译的不够好，看看校对者的意见吧
译文翻译完成，resolve #6445
=> 什么将会替代 JavaScript 呢？

TODO1/how-to-mock-services-using-mountebank-and-node-js.md
=> 如何使用 Mountebank 和 Node.js 来 Mock 服务

TODO1/bottom-navigation-bar-using-provider-flutter.md
=> 在 Flutter 中使用 Provider 构建底部导航栏

TODO1/eval-via-import.md
=> 使用 `import()` 执行 JavaScript 代码

TODO1/ces-learn-css-layout-part-1-flexbox.md
=> 趣味学习 CSS 布局 —— 第一部分：弹性布局

TODO1/un-places-to-learn-css-layout-part-2-grid-layout.md
=> 趣味学习 CSS 布局 —— 第二部分：网格布局

TODO1/styling-modern-web-apps.md
=> 关于现代应用样式的探讨

TODO1/flutter-state-management-setstate-bloc-valuenotifier-provider.md
…provider.md
译文翻译完成，resolve #6277
=> Flutter 的状态管理方案：setState、BLoC、ValueNotifier、Provider

TODO1/new-node-js-features.md
Node.js 新特性将颠覆 AI、物联网等更多惊人领域
译文翻译完成，resolve #6363
=> Node.js 新特性将颠覆 AI、物联网等更多惊人领域

TODO1/the-publisher-subscriber-pattern-in-javascript.md
=> JavaScript 的发布者/订阅者（Publisher/Subscriber）模式

TODO1/how-to-develop-a-generative-adversarial-network-for-a-1-dimensional-function-from-scratch-in-keras.md
=> 如何用 Keras 从头搭建一维生成对抗网络

TODO1/the-trick-to-animating-the-dot-on-the-letter-i.md
https://github.com/xitu/gold-miner/issues/6487
译文翻译完成，resolve #6487
=> 让字母“i”的点动起来的秘密

TODO1/react-svg-icon-components.md
=> 如何将 SVG 图标用做 React 组件？

TODO1/nodejs-jwt-authentication-oauth.md
你不需要 passport.js — node.js认证指南
译文翻译完成，resolve #6500
=> 你不需要 passport.js — node.js认证指南

TODO1/why-coding-your-own-makes-you-a-better-developer.md
https://github.com/xitu/gold-miner/issues/6441
=> 为什么自己动手写代码能让你成为更好的开发者

TODO1/dart-features-for-better-code-types-and-working-with-parameters.md
=> 类型及其在参数中的应用：能优化代码的的 Dart 特性

TODO1/my-personal-git-tricks-cheatsheet.md
=> 我个人的 Git 技巧备忘录

TODO1/understanding-recursion.md
理解递归、尾调用优化和蹦床函数优化
译文翻译完成，resolve #6554
=> 理解递归、尾调用优化和蹦床函数优化

TODO1/my-personal-git-tricks-cheatsheet.md
=> Translation/my personal git tricks cheatsheet.md

TODO1/syslog-the-complete-system-administrator-guide.md
https://github.com/xitu/gold-miner/issues/6344
译文翻译完成，resolve #6344
=> Syslog：系统管理员完整指南

TODO1/a-closer-look-at-the-provider-package.md
=> 深入解析 Flutter Provider 包

TODO1/json-parser-with-javascript.md
=> 使用 JavaScript 编写 JSON 解析器

TODO1/mathematical-programming-a-key-habit-to-built-up-for-advancing-in-data-science.md
…-in-data-science.md
译文翻译完成，resolve #6379
=> 数学编程  ——  一个为推进数据科学发展而培养的关键习惯

TODO1/how-to-write-video-chat-app-using-webrtc-and-nodejs.md
WebRTC 联手 Node.js：打造实时视频聊天应用
译文翻译完成，resolve #6586
=> WebRTC 联手 Node.js：打造实时视频聊天应用

TODO1/history-of-javascript.md
=> JavaScript 简史 补充修改

TODO1/how-to-build-a-blog-with-nest-js-mongodb-and-vue-js.md
文章翻译完成，不好意思拖了几天
译文翻译完成，resolve #6568
=> 如何用 Nest.js、MongoDB 和 Vue.js 搭建一个博客

TODO1/creating-website-sitemap.md
5 个简单步骤为您的网站创建 Sitemap
译文翻译完成，resolve #6590
=> 5 个简单步骤为您的网站创建 Sitemap

TODO1/webassembly-why-and-how-to-use-it.md
=> WebAssembly：带有代码示例的简单介绍

TODO1/learn-to-cache-your-nodejs-application-with-redis-in-6-minutes.md
用 6 分钟学习如何用 Redis 缓存您的 NodeJS 应用！
译文翻译完成，resolve #6673
=> 用 6 分钟学习如何用 Redis 缓存您的 NodeJS 应用！

TODO1/making-svg-icon-component-in-vue.md
=> 在 Vue 中编写 SVG 图标组件

TODO1/7-principles-of-icon-design.md
关于 icon 设计的 7 大准则
译文翻译完成，resolve #6700
=> 关于 icon 设计的 7 大准则

TODO1/stop-using-everywhere.md
=> 停止在任何地方使用 ===

TODO1/understanding-service-workers-and-caching-strategies.md
理解 Service Worker 和缓存策略
译文翻译完成，resolve #6668
=> 理解 Service Worker 和缓存策略

TODO1/btc-history-git.md
=> Git 的历史: 软件版本控制的统治之路

TODO1/password-hashing-pbkdf2-scrypt-bcrypt-and-argon2.md
=> 密码哈希的方法：PBKDF2，Scrypt，Bcrypt 和 ARGON2

TODO1/making-logs-colorful-in-nodejs.md
给 NodeJS 的 Logs 点颜色看看！
译文翻译完成，resolve #6757
=> 给 NodeJS 的 Logs 点颜色看看！

TODO1/whats-going-on-in-that-front-end-head.md
前端代码顶部的 Header 标签里都有些什么？
译文翻译完成，resolve #6761
=> 前端代码顶部的 Header 标签里都有些什么？

TODO1/5-secret-features-of-json-stringify.md
=> JSON.stringify() 的 5 个秘密特性

TODO1/how-can-cloud-services-help-improve-your-businessess-efficiency.md
=> 云服务如何帮助你提高业务效率？

TODO1/nestjs-basic-auth-and-sessions.md
NestJS 实现基本用户认证和会话
译文翻译完成，resolve #6627
=> NestJS 实现基本用户认证和会话

TODO1/6-best-javascript-frameworks-in-2020.md
=> 2020 年排名前 6 位的 JavaScript 框架

TODO1/create-a-line-chart-in-swiftui-using-paths.md
=> 用 SwiftUI 的 Paths 创建折线图

TODO1/why-is-object-immutability-important.md
=> 为什么对象不变性很重要？

TODO1/i-built-an-app-that-uses-all-7-new-features-in-javascript-es2020.md
使用 JavaScript ES2020 中所有的 7 个新特性构建 App
译文翻译完成，resolve #6877
=> 使用 JavaScript ES2020 中所有的 7 个新特性构建 App

TODO1/what-on-earth-is-the-shadow-dom-and-why-it-matters.md
=> Shadow DOM 到底是什么？它为什么重要？

TODO1/web-scraping-with-puppeteer-in-node-js.md
在 Node.js 中用 Puppeteer 实现网络爬虫
译文翻译完成，resolve #6948 
原始的 `.md` 文件中，第 111 行有个格式错误，是原作者的错误，我擅自更正了。
原始的 `.md` 文件中，第 121 行以下应该是一段代码块，原作者是用 iFrame 嵌入了 Carbon 的页面，可能转 `.md` 文件时丢失了，我也擅自补上了。
所以会出现英文和译文错行的问题，麻烦大家了。
=> 在 Node.js 中用 Puppeteer 实现网络爬虫

TODO1/polymorphic-react-components.md
=> 编写类型安全的多态 React 组件（不会导致 TypeScript 崩溃）

TODO1/11-chrome-apis-that-give-your-web-app-a-native-feel.md
11 个能让你的 App 像原生 App 的 Chrome API
译文翻译完成，resolve #6785
=> 11 个能让你的 App 像原生 App 的 Chrome API

TODO1/everything-you-need-to-know-about-javascript-symbols.md
关于 JavaScript 中 Symbol 数据类型你需要了解的一切
译文翻译完成，resolve #6801
=> 关于 JavaScript 中 Symbol 数据类型你需要了解的一切

TODO1/plain-javascript-versions-of-lodash-array-filtering-and-manipulation-methods.md
=> 纯 JavaScript 版本的 Lodash 数组 Filtering 和 Manipulation 方法

article/2020/latest-features-javascript-ecmascript-2020.md, article/2020/safe-recursion-with-trampoline-in-javascript.md
=> ECMAScript 2020 新特性

article/2020/will-ubuntu-20-04-steal-more-windows-users.md
=> Ubuntu 20.04 会不会偷走更多的 Windows 用户？

TODO1/javascript-top-level-await-in-a-nutshell.md
如何在 JavaScript 中使用新特性“顶层 await”
译文翻译完成，resolve #6770
=> 如何在 JavaScript 中使用新特性“顶层 await”

article/2020/css-fix-for-100vh-in-mobile-webkit.md
译文翻译完成，顺便修复了一下图片路径的问题，resolve #7114
=> 手机端 WebKit 内核浏览器 100vh 问题的 CSS 修复方法

article/2020/mvvm-in-swift-infinite-scrolling-and-image-loading.md
=> 在 Swift 中使用 MVVM 架构实现无限滚动和图片加载

article/2020/which-should-you-use-asynchronous-programming-or-multi-threading.md
=> 异步编程和多线程，我该选择哪个方案？

article/2020/which-should-you-use-asynchronous-programming-or-multi-threading.md
=> 修改格式——异步编程和多线程，我该选择哪个方案

article/2020/is-deno-a-threat-to-node.md
添加中文翻译。
等待自我校对及删除英文。
Resolved #7089
=> Deno 会对 Node 造成威胁吗？

article/2020/object-freeze-vs-object-seal-immutability.md
Object.freeze VS Object.seal —— JavaScript 数据不变性
译文翻译完成，resolve #7154
=> Object.freeze VS Object.seal —— JavaScript 数据不变性

article/2020/writing-tetris-in-python.md
=> 用 Python 写一个俄罗斯方块游戏

article/2020/understanding-why-a-database-deadlock-occurs.md
你理解数据库死锁发生的原因吗?
译文翻译完成，resolve #7142
=> 你理解数据库死锁发生的原因吗?

article/2020/how-i-learned-sass-in-20-hours-and-why-you-should-too.md
译文翻译完成，resolve #7159
我个人使用 Less 比较多，这篇文章的“学习路线”部分列举了大量 Sass 的有关术语，有的难以找到确切的解释，希望校对同学可以帮忙多看看。
=> 我是如何用 20 小时学会 Sass 的以及为什么你也应该这么做

article/2020/build-a-server-driven-ui-using-ui-components-in-swiftui.md
=> 在 SwiftUI 中构建服务端驱动的 UI 组件

article/2020/schema-org-the-popular-web-standard-youve-never-heard-of.md
=> Schema.org: 你未曾耳闻的流行网页标准 🤫

article/2020/user-defaults-in-swift.md
=> 在 Swift 使用 User Defaults 的小技巧

article/2020/whats-new-in-swift-5-3.md
=> Swift 5.3 的新功能，你了解吗?

integrals.md
GitHub 账号改名字和地址了
Origin romeo0906 https://github.com/Romeo0906
Current Herman https://github.com/actini
=> GitHub 账号改名字和地址了

article/2020/python-smart-coding-with-locals-and-global.md
译文翻译完成，resolve #7218
不得不说，这篇文章原作者写的真的一言难尽……
现在掘金已经什么样的文章都收了吗？
=> Python：使用 locals() 和 globals() 巧妙编程

article/2020/14-javascript-code-optimization-tips-for-front-end-developers.md
=> 给前端开发者的 14 个 JavaScript 代码优化建议

article/2020/performance-analysis-tools-for-front-end-development.md
=> 前端开发 8 大性能分析工具

article/2020/packaging-a-ui-library-for-distribution.md
=> 打包用于分发的 UI 库 —— 当你要发布一个 UI 组件库时，你可能需要遵守的指南

article/2020/8-unheard-of-browser-apis-you-should-be-aware-of.md
你应该了解的八种浏览器 API
译文翻译完成，resolve #7272
=> 你应该了解的八种浏览器 API

article/2020/detect-faces-texts-and-even-barcodes-with-chromes-shape-detection-api.md
=> 使用 Chrome 的 Shape Detection API 检测人脸，文本甚至条形码

article/2020/typescript-4-0-i-want-a-list-of-generic-params-with-good-labels.md
=> TypeScript 4.0 终于发布了我一直在等待的东西

TODO1/an-introduction-to-raspberry-pi-4-gpio-and-controlling-it-with-node-js.md
译文翻译完成，resolve #6749 resolve #6571
=> 使用 Node.js 控制树莓派 4 的 GPIO

article/2020/code-coverage-vue-cypress.md
=> Vue 应用的代码覆盖率

article/2020/5-lesser-known-features-of-chrome-devtools.md
最后一条，即第5条的图片加载可能有点问题
译文翻译完成，resolve #7410
=> 5 个鲜为人知的 Chrome 开发工具的特性

article/2020/auto-documenting-a-python-project-using-sphinx.md
=> 使用 Shpinx 为 Python 项目自动生成文档

article/2020/best-features-of-es2017-async-functions-and-arrays-and-shared-buffers.md
…buffers.md
翻译完成
译文翻译完成，resolve #7436
=> ES2017 最佳特性  —  数组中的异步函数以及共享缓冲区

article/2020/typescript-the-value-of-a-good-generic.md
=> TypeScript：一个好泛型的价值

article/2020/learn-about-swiftui-text-and-label-in-ios-14.md
=> 学习 SwiftUI 框架中 Text 和 Label 控件的用法（iOS 14）

article/2020/how-to-create-a-reusable-web-scraper.md, article/2020/improve-mongodb-performance-using-projection.md
=> 利用映射提高 MongoDB 性能

article/2020/using-service-workers-with-react.md
=> 在 React 中使用 Service Worker

article/2020/the-10-best-and-most-liked-flutter-packages.md
=> 10 款质量最佳最受欢迎的 Flutter 工具库

article/2020/mvc-vs-mvp-vs-mvvm.md
=> MVC、MVP、MVVM 对比

article/2020/nextjs-vs-nuxtjs-vs-gatsbyjs.md
=> NextJS vs. NuxtJS vs. GatsbyJS

article/2020/a-comprehensive-guide-to-slices-in-golang.md
=> Golang 切片综合指南

article/2020/react-native-vs-flutter-vs-ionic.md
=> 哪个跨平台框架才是最好的选择？React Native、Flutter 还是 Ionic。

article/2020/enhance-javascript-security-with-content-security-policies.md
译文翻译完成，resolve https://github.com/xitu/gold-miner/issues/7467
=> 内容安全策略提升 JavaScript 安全性

article/2020/responsive-font-size-using-vanilla-css.md
使用原生 CSS 设置响应式字体
译文翻译完成，resolve #7536
=> 使用原生 CSS 设置响应式字体

article/2020/exciting-features-of-javascript-es2021-es12.md
=> JavaScript ES2021 中激动人心的特性

article/2020/building-and-monitoring-your-first-github-actions-workflow.md
Github Actions 工作流的创建与跟踪
译文翻译完成，resolve #7589
=> Github Actions 工作流的创建与跟踪

article/2020/5-useful-things-the-spread-operator-can-do-in-javascript.md
=> 对象展开运算符在 JavaScript 中的 5 大应用

article/2020/web-locks-api-cross-tab-resource-synchronization.md
=> Web Locks API：跨 Tab 资源同步

article/2020/how-to-use-cookies-for-persisting-users-in-nextjs.md
=> 如何在 Nextjs 中使用 cookies 来持久化保存用户信息

article/2020/4-ways-to-communicate-across-browser-tabs-in-realtime.md
四种跨浏览器选项卡实时通信方法
译文翻译完成，resolve #7610
=> 四种跨浏览器选项卡实时通信方法

article/2020/5-reasons-why-you-should-use-svelte-for-front-end-development-in-2021.md
使用 Svelte 开发前端应用的五个理由
译文翻译完成，resolve #7625
=> 使用 Svelte 开发前端应用的五个理由

article/2020/demoforbeginner-what-is-wsgi.md
@lsvih 译文翻译完成，resolve #7511 
因原文某些格式不太规范，有对部分格式进行修改，未完全照搬原文格式：
1. 大小写规范：例如「github」改为「GitHub」，「python」改为「Python」。
2. 代码块：对文中提及的变量、函数使用反引号包裹，展现为行内代码格式，方便阅读。例如 application(environ, start_response) 改为 `application(environ, start_response)`。
3. 列表项：为全文统一，均在行末加入句号。
=> 给初学者的示例：什么是 WSGI？

article/2020/adaptive-video-with-css-math.md
使用原生 CSS 实现自适应视频
译文翻译完成，resolve #7506
=> 使用原生 CSS 实现自适应视频

article/2020/javascript-decorators-from-scratch.md
=> 从零开始了解 JavaScript 装饰器

article/2020/build-a-graphql-server-with-spring-boot-and-mysql.md
Build a GraphQL Server With Spring Boot and MySQL
翻译完成，resolve #7607
=> 使用 SpringBoot 和 MySQL 构建 GraphQL 服务端应用程序

article/2020/natural-language-processing-in-the-browser.md
=> 在浏览器中处理自然语言

article/2020/how-to-avoid-wifi-throttling-on-android-devices.md
=> 如何避免 Android 设备的 WiFi 扫描节流

article/2020/write-cleaner-code-by-using-javascript-destructuring.md
使用 JavaScript 解构让代码更优雅
译文翻译完成，resolve #7224
=> 使用 JavaScript 解构让代码更优雅

article/2020/how-to-useref-to-fix-react-performance-issues.md
=> 如何使用 useRef 修复 React 性能问题

article/2020/dark-theme-a-modern-ui-design.md
=> 黑暗主题 — 现代 UI 设计

article/2020/5-chrome-extensions-for-developers-productivity.md
=> 提高开发效率的五个 Chrome 扩展程序

article/2020/understanding-modules-and-import-and-export-statements-in-javascript.md
Change-Id: I97cb98d342924903db1a392064937f47a2005cce
@lsvih 译文翻译完成，resolve #7644
=> 理解 JavaScript 中模块的导入和导出

article/2020/understanding-react-portals.md
Change-Id: I448b4645934d9c71fd45dffa382e899efea2c04e
@lsvih 译文翻译完成，resolve #7616
=> 了解 React Portals（传送门）

article/2020/understanding-modules-and-import-and-export-statements-in-javascript.md
=> fix: 理解 JavaScript 中模块的导入和导出 —— 掘金发文前最后一次修改

article/2020/5-tips-for-better-typescript-code.md
=> TypeScript 的 5 个建议

article/2020/hunting-for-the-optimal-automl-library.md
=> 寻找最优化 AutoML 库

article/2020/exploring-constraintlayout-2-0-in-android.md
Helper Objects翻译为辅助布局，其实是和下面的文章内容相关的。
译文翻译完成，resolve #7405
=> 探索 Android 中的 ConstraintLayout 2.0

article/2020/loving-graphql-more-than-rest.md
=> 爱 GraphQL 胜过 REST

article/2021/the-different-types-of-browser-storage.md
=> 不同类型的浏览器存储

article/2020/why-you-should-make-your-code-as-simple-as-possible.md
=> fix: 为什么要让你的代码尽可能简单 —— 读者反馈修改

article/2020/flutter-may-or-may-not-be-the-next-big-thing-but-kotlin-multiplatform-is-here-to-stay.md
…latform-is-here-to-stay.md
提交翻译内容
译文翻译完成，resolve #7688
=> Flutter 可能是下一个大事件，但 Kotlin Multiplatform 一直都是大事件

article/2021/deconstructing-the-iconic-apple-watch-bubble-ui.md
=> 解构标志性的 Apple Watch Bubble UI

article/2020/widgets-on-ios.md
=> iOS 中的 widget

article/2021/top-5-icon-packs-for-web-apps-in-2021.md
=> 2021 年 Web 应用开发常用的五个图标库

article/2021/how-to-slow-down-a-for-loop-in-javascript.md
修改错误的校对者信息，resolve #7957 
- by [霜羽 Hoarfroster](https://github.com/PassionPenguin)
=> Fix metadata

TODO/11-top-designers-give-11-pieces-of-realistic-ux-advice.md, TODO/Introducing-Swift 3.0.md, TODO/OAuth2 Authentication with Lua.md, TODO/OptimizationTips.rst, TODO/effective-okhttp.md, TODO/freemium-conversion-rate/freemium-conversion-rate.md, TODO/guide-to-interviewing-for-product-design-internships.md, TODO/how-the-heck-does-async-await-work-in-python-3-5.md, TODO/i-m-a-web-developer-and-i-ve-been-stuck-with-the-simplest-app-for-the-last-10-days.md, TODO/lecture-1-what-is-product-design.md, TODO/python-3-an-intro-to-encryption.md, TODO/rxswift-at-first-sight.md, TODO/the-secret-to-writing-killer-product-copy.md
因为自己在前段时间修改了自己github的id，导致原有翻译和校对的地址出现404，因此申请修改。
@itcodes
=> 申请修改以前翻译&校对中自己的github地址

article/2021/how-to-use-indexeddb-a-nosql-db-on-the-browser.md
=> 如何在浏览器上使用 NoSQL 数据库 IndexedDB

article/2021/Which type of loop is fastest in JavaScript?.md
=> Update Which type of loop is fastest in JavaScript?.md

article/2021/6-regrets-i-have-as-a-react-developer.md
译文翻译完成，resolve #7964 
- by [霜羽 Hoarfroster](https://github.com/PassionPenguin)
=> 我后悔没有在成为 React 开发者之时做的 6 件事

article/2021/6-regrets-i-have-as-a-react-developer.md
译文校对完成，resolve #8063 @lsvih @Ivocin @itcodes
=> 我后悔没有在自己成为 React 开发者之前做的 6 件事情

article/2021/tutorial-d3-js-calendar-heatmap-(to-visualize-StackOverflow-Usage-Data).md
=> tutorial-d3-js-calendar-heatmap-(to-visualize-StackOverflow-Usage-Data)

article/2021/6-regrets-i-have-as-a-react-developer.md
Add proofreader information @lsvih @itcodes
=> Add proofreader information

article/2021/Building-an-SQL-Database-Audit-System-Using-Kafka,-MongoDB-and-Maxwell's-Daemon.md
译文翻译完成，resolve #8103 
@lsvih @PassionPenguin
=> 使用 Kafka、MongoDB 和 Maxwell's Daemon 构建 SQL 数据库审计系统

article/2021/understanding-css-grid.md
译文翻译完成，resolve #8106 @lsvih 
- by [霜羽 Hoarfroster](https://github.com/PassionPenguin)
=> 自适应 CSS 栅格：自由布局的最终版本

article/2021/how-an-anti-typescript-javascript-developer-like-me-became-a-typescript-fan.md
=> 和我一样是 TypeScript 黑粉的 “JavaScript 开发者” 是怎样黑转粉的？

article/2021/using-immer-with-react-a-simple-solutions-for-immutable-states.md
=> 在 React 中使用 Immer 管理不可变状态

article/2021/Deno-1-8-Release-Notes.md
=> Deno 1.8 发行公告

article/2021/new-features-chrome-88.md
=> Chrome 88 DevTools 中的新功能

article/2021/Go-developer-survey-2020-results.md
=> add 'Go-developer-survey-2020-results.md'

article/2021/native-splash-screen-in-flutter-using-lottie.md
翻译完啦 @lsvih ψ(｀∇´)ψ
resolve #7981
=> 在 Flutter 项目中使用 Lottie 构建原生 Splash 启动页

article/2021/Angular-vs-React-vs-Vue-Which-Framework-is-Best-in-2021.md, article/2021/Web-Performance-for-Product-Managers.md
=> Angular-vs-React-vs-Vue-Which-Framework-is-Best-in-2021

article/2021/raspberry-pi’s-ninth-birthday-9-things-you-might-not-know.md
=> Raspberry Pi 九岁啦：你可能不知道的 9 件事

article/2021/Angular-vs-React-vs-Vue-Which-Framework-is-Best-in-2021.md
=> Revert "2021 年 Angular vs. React vs. Vue 前端框架对比"

article/2021/snowpack-an-alternative-build-tool-to-webpack.md
=> Snowpack：一个可替代 Webpack 的构建工具

article/2021/time-for-next-gen-codecs-to-dethrone-jpeg.md, article/2021/time_for_next_gen_codecs_to_dethrone_jpeg.md
=> Created time-for-next-gen-codecs-to-dethrone-jpeg.md

article/2021/gcp-healthcare-consent-api.md
=> fix some typos in gcp-healthcare-consent-api

article/2021/dropbox-reveals-Atlas.md
=> Dropbox 公布了 Atlas —— 一个托管服务编排平台

article/2021/google-oss-fuzz-extends-fuzzing-to-java-apps.md
译文翻译完成，resolve #8238
---
@lsvih
=> Google 的开源模糊测试工具 OSS-Fuzz 现在支持 Java 应用了

article/2021/The-End-of-Applets.md, article/2021/react-vs-vue-in-2021-best-javascript-framework.md
=> The end of applets

article/2021/the-arrival-of-java-16.md
=> Recommendation: The Arrival of Java 16

article/2021/microsoft-makes-changes-to-windows-10-inbox-apps-with-latest-dev-channel-test-build.md
=> Recommendation: Microsoft makes changes to Windows 10 inbox apps with latest Dev Channel test build

article/2021/chrome-90-beta-av1-encoder-for-webrtc.md
=> Recommendation: Chrome 90 Beta: AV1 Encoder for WebRTC, New Origin Trials, and More

article/2021/svelte-nodegui-native-desktop.md
=> Recommendation: New Svelte NodeGui Allows Creating Native Desktop Applications with Qt and Svelte

article/2021/the-arrival-of-java-16.md
=> Java 16 发布啦

article/2021/android-new-features-spring-2021.md
=> 你的 Android 设备现在更安全了 —— 还有 5 项别的新功能！

article/2021/microsoft-makes-changes-to-windows-10-inbox-apps-with-latest-dev-channel-test-build.md
=> 微软在 Windows 最新的测试版中内置了 Windows Terminal

article/2021/svelte-nodegui-native-desktop.md
=> Svelte NodeGUI 发布了！我们现在可以使用 Qt 和 Svelte 构建原生桌面端应用程序

article/2021/chrome-90-beta-av1-encoder-for-webrtc.md
=> Chrome 90 Beta 版本更新，支持 WebRTC AV1 编码器，新的 Origin Trials，还有更多等着你来～

article/2020/handling-location-permissions-in-ios-14.md
在 iOS 14 中处理位置权限和管理近似地址访问
译文翻译完成，resolve #7325
=> 在 iOS 14 中处理位置权限和管理近似地址访问

article/2020/implementing-monte-carlo-tree-search-in-node-js.md
=> 使用 Node.js 实现蒙特卡洛树搜索

article/2021/react-vs-vue-in-2021-best-javascript-framework.md
=> Fix author name

article/2021/introducing-page-shield.md
resolve #8331, PTAL @lsvih @husiyu
=> Recommendation: Page Shield: Protect User Data In-Browser

article/2021/These-Modern-Programming-Languages-Will-Make-You-Suffer.md
=> Add modern

article/2021/2021-03-15-highlights-from-git-2-31.md
Git 2.31 中的闪光点
译文翻译完成，resolve #8252
=> Git 2.31 中的闪光点

article/2021/expert-hackers-used-11-zerodays-to-infect-windows-ios-and-android-users.md
译文翻译完成，resolve #8285 @lsvih
校对者可参考
https://googleprojectzero.blogspot.com/2021/03/in-wild-series-october-2020-0-day.html
https://www.163.com/dy/article/G5FJA3280511D6RL.html
=> “高级”黑客使用 11 个零日漏洞去感染 Windows、iOS 还有 Android 用户

article/2021/webpacks-hot-module-replacement-feature-explained.md
=> 详细解读 Webpack 的模块热替换功能

article/2021/1993-cgi-scripts-and-early-server-side-web-programming.md
=> 1993 年的 CGI 脚本和早期服务端 Web 编程

article/2021/deepmind-NFNets-deep-learning.md
=> 谷歌 DeepMind 发布 NFNet：高效的深度网络

article/2021/The-End-of-Applets.md
=> Applets 应用程序的终结

article/2021/the-new-king-of-bundlers-is-here-all-bow-before-vitejs.md
=> 新型前端构建工具 Vitejs 开发使用

article/2021/when-compat-libraries-do-not-save-you.md
=> Recommendation: When compat libraries do not save you

article/2021/telegram-like-uploading-animation.md
=> Recommendation: telegram-like-uploading-animation.md

article/2021/6-amazing-free-tools-that-will-save-you-some-time-when-u-are-building-websites-especially-for-non-designer-developers.md
resolve #8321, PTAL @lsvih @husiyu
=> Recommendation: 6 amazing free tools that will save you some time when u are building websites. (Especially for 'non-designer' developers)

article/2021/using-github-code-scanning-and-codeql-to-detect-traces-of-solorigate-and-other-backdoors.md
resolve #8322, PTAL @lsvih @husiyu
=> Recommendation: Using GitHub code scanning and CodeQL to detect traces of Solorigate and other backdoors

article/2021/flutter-quote-app.md
=> Recommendation: Flutter quotes app

article/2021/5-Reasons-to-Switch-from-React-to-Next-js.md
=> 5 Reasons to Switch from React to Next.js

article/2021/grafana-managed-observability.md
=> Grafana 为其可视化产品栈新增企业级日志服务

article/2021/6-amazing-free-tools-that-will-save-you-some-time-when-u-are-building-websites-especially-for-non-designer-developers.md
=> 没有 UI 团队怎么办？分享 6 款能为独立网页开发者提效的免费工具

article/2021/time-for-next-gen-codecs-to-dethrone-jpeg.md
=> 到了下一代图像编码来罢黜 JPEG 编码的时候了

article/2021/using-github-code-scanning-and-codeql-to-detect-traces-of-solorigate-and-other-backdoors.md
使用 GitHub 代码扫描和 CodeQL 工具检测 Solorigate 等后门程序
译文翻译完成，resolve #8425
=> 使用 GitHub 代码扫描和 CodeQL 工具检测 Solorigate 等后门程序

.github/workflows/translator-application.yaml
see https://github.com/marketplace/actions/close-issue
ptal @kezhenxu94
=> feat: automatically close issue

article/2021/top-7-dart-tips-and-tricks-for-cleaner-flutter-apps.md
译文翻译完成，resolve #8214 
---
@lsvih
=> 7 个最能用于构造更整洁的 Flutter 应用的 Dart 小贴士和小技巧

article/2021/web-share-for-modern-web-apps.md
=> 现代 Web 应用程序中的 Web 分享

article/2021/20-go-packages-you-can-use-in-your-next-project.md
=> 可以在下一个项目中使用的 20 个 Go 三方库

article/2021/cross-site-scripting.md
译文翻译完成，resolve https://github.com/xitu/gold-miner/issues/8465
=> 跨站脚本攻击（XSS）

article/2021/5-Reasons-to-Switch-from-React-to-Next-js.md
=> 从 React 转换到 Next.js 的五个理由

article/2021/introducing-page-shield.md
=> Page Shield：保护浏览器中的用户数据

article/2021/better-privacy-with-chromiums-privacy-sandbox.md
Chromium 隐私沙盒让用户隐私更安全
译文翻译完成，resolve #8449
=> Chromium 隐私沙盒让用户隐私更安全

article/2021/11-easy-ui-design-tips-for-web-devs-j3j.md
=> 为 Web 开发同学准备的 11 个简单实用的 UI 设计小技巧

article/2021/5-css-practices-to-avoid-as-a-web-developer.md
=> Web 开发者应该避免的 5 个 CSS 的做法

article/2021/brown-green-language.md
译文翻译完成，resolve #8497
漫画内文本的翻译我放在了 Alt 标签里：）
=> “绿色”和“棕色”的编程语言

article/2021/everything-about-the-latest-ecmascript-release-ecmascript-2021.md, article/2021/javascript-typed-arrays.md
=> 有关 ECMAScript 最新版本的所有信息｜ECMAScript 2021

article/2021/hookrouter-a-modern-approach-to-react-routing.md
=> 现代化的 React 路由 Hookrouter 开发使用

article/ECMA-TC39/How-to-make-a-Pull-Request-against-the-ECMAScript-specification.md
=> How to make a Pull Request against the ECMAScript specification

article/ECMA-TC39/Presenting-a-Proposal-to-TC39.md, article/ECMA-TC39/Reading-a-proposal-draft.md
=> Reading a proposal draft

article/2021/16px-or-larger-text-prevents-ios-form-zoom.md
=> Recommendation: 16px-or-larger-text-prevents-ios-form-zoom.md

article/2021/auto-generated-social-media-images.md
=> Recommendation: Auto-Generated Social Media Images

article/2021/custom-state-pseudo-classes-in-chrome.md
=> Recommendation: Custom State Pseudo-Classes in Chrome

article/2021/deep-dive-cors-history-how-it-works-best-practices.md
=> 深入理解 CORS：发展史、工作原理和最佳实践

integrals.md
=> 恢复 revert changes

article/2021/speed-up-your-angular-projects-by-10x-with-gpu-js.md
将标题中的 Angular.js 修改为 Angular。Angular 和 Angular.js 指代的不是一个框架。为避免误解，建议修改。
根据官方文档 [关于 AngularJS 与 Angular 概念的快速参考](https://angular.cn/guide/ajs-quick-reference)
> Angular 这个名字专指现在和未来的 Angular 版本，而 AngularJS 专指 Angular 的所有 1.x 版本。
且观看文章全文，提到的都是最新的 Angular 而不是 1.x 版本
因此为避免误解，建议修改。
https://github.com/xitu/gold-miner/blob/master/article/2021/speed-up-your-angular-projects-by-10x-with-gpu-js.md
=> 文章标题校正：将标题中的 Angular.js 修改为 Angular

article/2021/5-strategies-to-reduce-frontend-build-time-with-ci-cd.md
=> 使用 CI/CD 优化前端构建的五种策略

article/2021/next-gen-css-container.md
=> Recommendation: Next Gen CSS: @container

article/2021/new-standards-to-access-user-device-hardware-using-javascript.md
=> 用 JavaScript 访问用户设备硬件的新标准

article/2021/auto-generated-social-media-images.md
=> 简述自动生成的社交媒体图片

article/ECMA-TC39/How-to-participate-in-meetings.md
=> fix imgs URL

article/2021/all-you-need-to-know-about-higher-order-functions-in-javascript.md
=> 简述 JavaScript 高阶函数的开发使用

article/2021/next-gen-css-container.md
=> 下一代 CSS：@container

article/2021/making-javascript-run-fast-on-webassembly.md
让 JavaScript 在 WebAssembly 上疾速运行
译文翻译完成，resolve #8801
=> 让 JavaScript 在 WebAssembly 上疾速运行

article/2021/using-interfaces-to-write-better-php-code.md
=> Recommendation: using-interfaces-to-write-better-php-code.md

article/2021/http-strict-transport-security-faqs.md, others.md
=> HTTP 严格传输安全协议常见问题解答

article/2021/variable-aspect-ratio-card-with-conic-gradients-meeting-along-the-diagonal.md
=> 对角线分割的圆锥渐变式可变纵横比卡片

article/2021/how-a-cache-stampede-caused-one-of-facebooks-biggest-outages.md
=> 缓存踩踏事件是如何导致 Facebook 最大的宕机事件之一发生的

article/2021/so-whats-the-state-of-jquery-in-2021.md
2021 年，jQuery 过得还好吗？
译文翻译完成，resolve #8949
=> 2021 年，jQuery 过得还好吗？

article/2021/5-reasons-why-flutter-is-better-than-react-native.md
=> Flutter 比 React Native 更优秀的五个理由

article/2021/graph-data-structure-implementation-in-javascript.md
=> JavaScript 实现图数据结构

article/2021/how-its-made-i-o-photo-booth.md
=> 我们是怎么做到的：Google I/O Photo Booth

article/2021/using-bloc-pattern-with-react.md
=> 在 React 中使用 BLoC 模式

article/2021/11-rare-javascript-one-liners-that-will-amaze-you.md
=> 11 个让你惊叹的 罕见 JavaScript 单行代码

article/2021/selector-nesting-has-come-to-css.md
=> CSS 选择器嵌套已经来了🤯🤯🤯 ！

article/2021/send-http-requests-as-fast-as-possible-in-python.md
=> 在 Python 中用最快的速度发送 HTTP 请求

article/2021/replace-null-with-es6-symbols.md
=> 如何使用 ES6 新增 Symbols 代替 null

article/2021/10-awesome-things-you-can-do-with-github-dev.md
=> 可以在 GitHub.dev 做的十件有趣的事

article/2021/running-javascript-in-webassembly.md
=> 使用 WasmEdge 在 WebAssembly 中运行 JavaScript

article/2021/avoid-trusting-const-in-javascript.md
=> 不要信任 JavaScript 里的 `const`

README.md, TODO1/4-css-filters-for-adjusting-color.md, TODO1/a-tale-of-webpack-4-and-how-to-finally-configure-it-in-the-right-way.md, TODO1/an-overview-of-go-tooling.md, TODO1/designing-for-the-web-ought-to-mean-making-html-and-css.md, TODO1/enough-to-decide.md, TODO1/how-to-develop-react-js-apps-fast-using-webpack-4.md, TODO1/javascript-generator-yield-next-async-await.md, TODO1/mdc-104-flutter.md, TODO1/rust-2018-is-here-but-what-is-it.md, TODO1/the-absolute-easiest-way-to-debug-node-js-with-vscode.md, TODO1/the-evolution-of-the-design-from-ux-towards-personal-experience.md, article/2020/8-scss-best-practices-to-keep-in-mind.md, article/2020/how-to-create-a-reusable-web-scraper.md, article/2021/custom-state-pseudo-classes-in-chrome.md, backend.md, front-end.md, integrals.md
resolve https://github.com/xitu/gold-miner/issues/9172
=> other: 更新 iceytea 的 github 链接

article/2021/simulating-interplanetary-space-travel-in-python.md
=> 使用 Python 模拟实现行星际空间旅行

article/2022/Stop Building Your UI Components like this❌.md
新文更新。Stop Building Your UI Components like this❌
=> Create Stop Building Your UI Components like this❌.md

article/2022/Install-and-uninstall-WasmEdge.md
=> WasmEdge 的安装与卸载

article/2021/pipe-operations-in-python.md
=> 如何使用 Python 管道 Pipe 高效编码

article/2022/Stop-Building-Your-UI-Components-like-this.md
=> 停止这样构建你的组件❌

article/2022/javascript-frontend-speed-is-the-next-big-thing.md
=> 何时能有更快更强的前端开发框架

article/2022/send-data-to-the-server-when-the-user-navigates-to-another-page-using-javascript.md
=> 当用户跳转到其它页面时，使用 JavaScript 发送数据给服务器

article/2021/using-interfaces-to-write-better-php-code.md
=> 【续】使用接口编写更优雅的 PHP 代码

article/2022/pyscript-unleash-the-power-of-python-in-your-browser.md
=> PyScript — 在浏览器中释放 Python 的力量

TODO/how-javascript-works-the-building-blocks-of-web-workers-5-cases-when-you-should-use-them.md
添加了基于异步编程的 Scaler 主题异步 JavaScript 页面。我认为这将帮助所有学习者通过示例理解异步编程。请检查建议的更改。希望这个贡献有所帮助
=> 添加了一个有用的链接

article/2022/webrtc-vs-websockets.md
译文翻译完成，resolve #9398
抓取的 md 文件有很多缺失的图片和文字内容，已经按照原文补充，校对的同志可以参考[原文](https://requestum.com/webrtc-vs-websockets)
=> WebRTC 与 WebSockets 教程 — Web 端的实时通信

article/2022/top-10-java-language-features.md
=> 十大 Java 语言特性

article/2022/using-redis-on-cloud-here-are-ten-things-you-should-know.md
=> 云上使用 Redis？你应该知道这十件事

article/2022/implementing-bitcask-a-log-structured-hash-table.md
=> 实现 Bitcask ，一种日志结构的哈希表

article/2022/webgpu-computations-performance-in-comparison-to-webgl.md
=>  WebGPU 与 WebGL 的计算性能差异

article/2023/achieve-nextjs-mastery-build-a-sales-page-with-stripe-and-airtable.md
Achieve NextJS Mastery: Build a Sales Page with Stripe and Airtable
译文翻译完成，resolve #id
=> Achieve NextJS Mastery: Build a Sales Page with Stripe and Airtable

article/2020/10-awesome-chrome-flags-you-should-enable-right-now.md, article/2020/unexpected-app-crashes-on-android-and-how-to-deal-with-them.md, article/2021/3-fallback-techniques-to-support-css-grid-in-any-browser.md
=> Proofreading 1
