xitu/gold-miner

- README.md
- TODO/retrofit-getting-started.md
translate retrofit-getting-started finished
>  translate retrofit-getting-started finished

- TODO/exploring-the-product.md
这篇文章在ReadMe的列表中叫做《探索 Stripe Dashboard 产品设计之道》。
不足之处还恳请指正。
> 已完成《exploring-the-product》的翻译

- TODO/how-to-improve-quality-and-syntax-of-your-android-code.md
> 《How to improve quality and syntax of your Android code》翻译初稿完成

- TODO/25-core-data-in-ios10-nspersistentcontainer.md
> 完成: iOS 10 中的 NSPersistentContainer

- TODO/typescript-getting-popular.md
> * 原文地址：[Why TypeScript Is Growing More Popular](https://thenewstack.io/typescript-getting-popular/)
> * 原文作者：[Mary Branscombe](https://thenewstack.io/author/marybranscombe/)
> * 译文出自：[掘金翻译计划](https://github.com/xitu/gold-miner)
> * 掘金issue：https://github.com/xitu/gold-miner/issues/1627
> * 译者：[loveky](https://github.com/loveky)
> * 校对者：
> 为何 TypeScript 愈发流行了？

- TODO/web-developer-security-checklist.md
这是小弟第一次翻译文章，有点紧张。
这篇文章的专业术语好多...翻译有一些地方求各位大佬一起探讨。
打？？？的地方都是个人觉得翻译得不太好但不知道怎么表达才好的= =...
> Web 开发者安全清单

- TODO/write-safer-and-cleaner-code-by-leveraging-the-power-of-immutability.md
[issues 1684](https://github.com/xitu/gold-miner/issues/1684)
@sqrthree 翻译初稿
> 利用“Immutability（不可变性）”编写更为简洁高效的代码

- TODO/a-follow-up-on-how-to-store-tokens-securely-in-android.md
非常抱歉，这两天有点事，延期了两天。
对应 ISSUE：https://github.com/xitu/gold-miner/issues/1655
> 再谈如何安全地在 Android 中存储令牌

- TODO/kotlin-its-the-little-things.md
> Kotlin：小菜一碟

- TODO/how-to-get-the-most-out-of-the-javascript-console.md
> 如何充分利用 JavaScript 控制台

- TODO/server-side-react-rendering.md
[issue链接1825](https://github.com/xitu/gold-miner/issues/1825)
> React 在服务端渲染的实现

- TODO/What-would-be-your-advice-to-a-software-engineer-who-wants-to-learn-machine-learning.md
> 你会给想学习机器学习的软件工程师提出什么建议？

- TODO/functional-programming-in-javascript-is-an-antipattern.md
> Javascript 的函数式编程是一种反模式

- TODO/exploring-kotlins-hidden-costs-part-1.md
[Exploring Kotlin’s hidden costs — Part 1](https://github.com/xitu/gold-miner/issues/1812)
初翻完成，请校对大佬指正T__
Issue 地址：#1812
> 探索 Kotlin 中的隐性成本（第一部分）

- TODO/on-strategies-to-apply-kotlin-to-existing-java-code.md
> 将 Kotlin 应用于现有 Java 代码的策略

- TODO/upcoming-regexp-features.md
> 即将到来的正则表达式新特性

- TODO/user-breakpoints-in-xcode.md
> Xcode 中的用户断点

- TODO/deep-learning-1-setting-up-aws-image-recognition.md
> 深度学习系列1：设置 AWS & 图像识别

- TODO/how-chat-bots-work.md
> 机器之魂：聊天机器人是怎么工作的

- TODO/building-ar-game-arkit-spritekit.md
> 巧用 ARKit 和 SpriteKit 从零开始做 AR 游戏

- TODO/how-to-do-proper-tree-shaking-in-webpack-2.md
> 如何在 webpack2 中使用 tree-shaking

- TODO/javascript-debugging-tips.md
> 14 个你可能不知道的 JavaScript 调试技巧

- TODO/function-caller-considered-harmful.md
function.caller 被认为是有害的
译文翻译完成，resolve #3379
> function.caller 被认为是有害的

- TODO/how-to-javascript-in-2018.md
> 2018 如何玩转 JavaScript

- TODO/surprising-polymorphism-in-react-applications.md
> React 应用中 “神奇” 的多态—性能隐患

- TODO/enabling-proguard-in-an-android-instant-app.md
在 Android Instant App（安卓即时应用程序）中启用 ProGuard （混淆）
译文翻译完成，resolve #3298
> 在 Android Instant App（安卓即时应用程序）中启用 ProGuard（混淆）

- TODO1/wwdc-2018-rumors-ios-12-new-macbook-air-ipad-pro-homepod.md
WWDC 2018：关于iOS 12、iPad Pro、新MacBooks或者更多产品的所有预测
译文翻译完成，resolve #3873
> WWDC 2018：关于iOS 12、iPad Pro、新MacBook及更多产品的所有预测

- TODO1/7-rules-for-creating-gorgeous-ui-part-2.md
> 创造华丽 UI 的 7 个规则（Part 2）

- TODO1/maybe-you-dont-need-rust-to-speed-up-your-js-1.md
或许你并不需要 Rust 和 WASM 来提升 JS 的执行效率 — 第一部分
译文翻译完成，resolve #3930
> 或许你并不需要 Rust 和 WASM 来提升 JS 的执行效率 — 第一部分

- TODO1/learn-bootstrap-4-in-30-minute-by-building-a-landing-page-website-guide-for-beginners.md
用30分钟建立一个网站的方式来学习Bootstrap 4
译文翻译完成，resolve #4167
> 用 30 分钟建立一个网站的方式来学习 Bootstrap 4

- TODO1/introducing-spaceace-a-new-kind-of-front-end-state-library.md
> SpaceAce 了解一下，一个新的前端状态管理库

- TODO1/what-is-modular-css.md
> 什么是模块化 CSS？

- TODO1/native-web-components.md
> 用 Shadow DOM v1 和 Custom Elements v1 实现一个原生 Web Component

- TODO1/compromised-npm-package-event-stream.md
> 被污染的 npm 包：event-stream

- TODO1/data-visualization-with-bokeh-in-python-part-ii-interactions.md
> 利用 Python中的 Bokeh 实现数据可视化，第二部分：交互

- TODO1/an-introduction-to-css-shapes.md
> CSS Shapes 简介

- TODO1/rust-2018-is-here-but-what-is-it.md
> Rust 2018 已经发布...但它是到底什么呢？

- TODO1/can-you-console-log-in-jsx.md
> 在 JSX 代码中可以加入 console.log 吗？

- TODO1/swift-api-pollution.md
* 标题： API Pollution in Swift Modules
* 原文链接：[API Pollution in Swift Modules](https://nshipster.com/swift-api-pollution/)
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO1/swift-api-pollution.md)
* PR 地址：
* 文章分类：**iOS**
*  **注意：文件位置在 `TODO1` 文件夹中，不是之前的 `TODO` 了。**
---
* 翻译时间： 天
* 校对时间： 天
* 翻译积分： 分
* 校对积分： 分
* [积分有什么用](https://github.com/xitu/gold-miner/wiki)
> 增加文章 swift-api-pollution.md

- TODO1/tips-to-use-VSCode-more-efficiently.md
帮你高效使用 VS Code 的秘诀
译文翻译完成，resolve #5750
> 帮你高效使用 VS Code 的秘诀

- TODO1/understanding-mixins-in-vue-js.md
> 理解 Vue.js 中的 Mixins

- TODO1/you-should-never-ever-run-directly-against-node-js-in-production-maybe.md
你也许永远不要针对生产中的 Node.js 运行
译文翻译完成，resolve #5751
> 如果可以，永远不要在生产中直接运行 Node.js

- TODO1/understanding-javascript-async-and-await-with-examples.md
> 通过一些例子深入了解 JavaScript 的 Async 和 Await

- TODO1/how-to-build-a-cli-with-node-js.md
> 如何使用 Node.js 构建一个命令行界面（CLI）

- TODO1/picking-apart-stackoverflow-what-bugs-developers-the-most.md
> 剖析 Stack Overflow，开发者遇到最多的的 Bug 是哪些？

- TODO1/android-data-binding-library-from-observable-fields-to-livedata-in-two-steps.md
Android 数据绑定库 — 从可观察域到 LiveData 仅需两步
译文翻译完成，resolve #5953
> Android 数据绑定库  — 从可观察域到 LiveData 仅需两步

- TODO1/swiftwebui.md
> Web 端的 SwiftUI：SwiftWebUI

- TODO1/testing-react-apps-with-cypress.md
> 使用 Cypress 进行 React 应用的端到端测试

- TODO1/killing-a-process-and-all-of-its-descendants.md
> 如何杀死一个进程和它的所有子进程

- TODO1/flutter-infinite-listview-with-redux.md
> Flutter: 使用 Redux 实现无限 ListView

- TODO1/how-we-ditched-redux-for-mobx.md
> 我们为何抛弃 Redux 拥抱 MobX

- TODO1/history-of-javascript.md
译文翻译完成，resolve #6603
使用了 Markdown 扩展的脚注功能，Github 预览不支持显示，掘金上没有问题。
> JavaScript 简史

- TODO1/how-to-write-beautiful-and-meaningful-readme-md-for-your-next-project.md
如何写出优雅且有意义的 README.md
译文翻译完成，resolve #6670
> 如何写出优雅且有意义的 README.md

- TODO1/image-inpainting-humans-vs-ai.md
图像修复：人类和 AI 的对决
第一次翻译~希望校对大大们多给些建议
译文翻译完成，resolve #6682
> 图像修复：人类和 AI 的对决

- TODO1/high-speed-inserts-with-mysql.md
> MySQL 最佳实践—— 高效插入数据

- TODO1/separation-of-data-and-ui-in-your-web-app.md
> Web 应用程序中的数据和 UI 分离

- TODO1/5-ways-to-create-a-settings-icon.md
5 步创建一个 Settings icon
译文翻译完成，resolve #6780
> 创建一个 Settings icon 的五种方法

- TODO1/why-math-max-is-less-than-math-min-in-javascript.md
> 在 JavaScript 中为什么 Math.max() 会比 Math.min() 小？

- TODO1/5-optimization-tips-for-your-mobile-web-app-for-higher-user-retention.md
> 5 个优化技巧助你提高移动 Web 应用的用户留存率

- article/2020/safe-recursion-with-trampoline-in-javascript.md
Safe Recursion with Trampoline in JavaScript
译文翻译完成，resolve #7048
> 用 JavaScript 中的蹦床函数实现安全递归

- article/2020/swiftui-dark-mode-the-easiest-way.md
译文翻译完成，resolve #7698 
其中color asset没有翻，因为看到安卓的glossary说asset不翻。标题用“黑暗模式”是因为咱们这里其他的文章也是这么翻的。
> SwiftUI 黑暗模式——最简单的方法

- article/2021/importing-json-modules-in-typescript.md
译文翻译完成，resolve #7925 @lsvih :)
- by 苏苏的 [霜羽 Hoarfroster](https://github.com/PassionPenguin)
> 在 TypeScript 中引入 JSON 模块

- article/2021/flutter-creating-elegant-uis-with-containers.md
译文翻译完成，resolve #7911 @lsvih 
- by 苏苏的 [霜羽 Hoarfroster](https://github.com/PassionPenguin)
> 使用 Flutter 的 Container 控件构建优美的用户界面

- article/2021/ultimate-guide-to-swiftui2-application-lifecycle.md
> SwiftUI 2 应用生命周期的终极指导

- article/2020/example-of-a-machine-learning-algorithm-to-predict-spam-emails-in-python.md
> Python 开发垃圾邮件检测应用

- article/2021/should-you-compile-your-javascript-code.md
译文翻译完成 ψ(｀∇´)ψ，resolve #7970 
- by [霜羽 Hoarfroster](https://github.com/PassionPenguin)
> 你应该编译你的 JavaScript 代码吗？

- article/2021/quick-overview-of-http-requests-cross-origin-resource-sharing-cors.md
> 简述 HTTP 请求与跨域资源共享 CORS

- article/2021/5-reasons-why-Deno-will-stop-using-TypeScript- StartFunction.md
> Deno 将停用 TypeScript 的五个原因

- article/2021/undefined-null-revisited.md
> 重新审视 undefined 和 null

- article/2021/monads-for-javascript-developers.md
> 面向 JavaScript 开发人员的 Monads

- article/2021/from-rxjava-2-to-kotlin-flow-threading.md
resolve #7974 @lsvih ψ(｀∇´)ψ
等待大佬们的校对～
> 从 RxJava 2 转向使用 Kotlin 流：多线程

- article/2021/6-alternatives-to-classes-in-python.md
译文翻译完成，resolve #8144 
第一次尝试 python 文章，大大们帮偶狠狠挑挑刺
> Python 类的 6 种替代方案

- article/ECMA-TC39/How-to-make-a-Pull-Request-against-the-ECMAScript-specification.md
> 如何针对 ECMAScript 规范创建一个拉取请求

- article/ECMA-TC39/How-to-experiment-with-a-proposal-before-Stage-4.md
忘了有这一茬，以为认领的那几个全翻译了，实在抱歉……
@lsvih @zaviertang 翻译完成，请查收：）～ 🎉
---
resolve #8609
> 如何在第 4 阶段之前体验一个提案

- article/2021/v8-sparkplug-compiler.md
根据上下文和原文可知，「它依赖于 TurboFan 生成的字节码」应属于译者笔误。
> 修复 v8-sparkplug-compiler 中的笔误
