- TODO/javascript-developer-survey-results.md
> 《JavaScript 开发者年度调查报告》翻译完成

- TODO/Cocoa-Architecture-Dropped-Design-Patterns.md
> Translated Cocoa Architecture: Dropped Design Patterns

- TODO/must-see-javascript-dev-tools-that-put-other-dev-tools-to-shame.md
> 《2015 年底 JS 必备工具集》翻译完成

- TODO/effective-okhttp.md
可能有些语句不够通顺，你们快来指出来  `_(:зゝ∠)_`
@laobie 快来校对
@Glowin 江江再帮忙找一个人来校对吧 :)
> 《如何更高效的使用 okhttp》初稿完成

- TODO/OAuth2 Authentication with Lua.md
> OAuth2 Authentication with Lua

- TODO/how-we-css-at-bigcommerce.md
> 有一处空格位置打错了，重新merge一下

- TODO/permissions-part-1.md
- TODO/permissions-part-2.md
> Revert "《深入浅出Android权限（一）》翻译完成"

- TODO/rxswift-at-first-sight.md
> finish rxswift at first sight

- TODO/Introducing-Swift 3.0.md
> 翻译完成 Introducing-Swift 3.0

- TODO/using-concurrency-and-speed-and-performance-on-android.md
文章：#161 using-concurrency-and-speed-and-performance-on-android
> Android 开发中利用异步来优化运行速度和性能 翻译完成

- TODO/high-level-reactivity.md
> Reactive GraphQL Architecture 翻译完成

- TODO/building-a-kotlin-project.md
翻译完成：building-a-kotlin-project.md
> Translation finished: Building a Kotlin Project (Part I)

- TODO/building-a-kotlin-project-2.md
> Building a Kotlin Project - 2 漏网之鱼

- TODO/embedding-lua-in-the-web.md
> embedding-lua-in-the-web 初稿完成

- TODO/Testing-Schemes.md
> Using Xcode's Schemes to run a subset of your tests - translated.

- TODO/Breaking-Swift-with-reference-counted-structs.md
> Breaking Swift with reference counted structs - First revision.

- TODO/optimize-battery-life-with-androids-gcm-network-manager.md
add md file optimize-battery-life-with-androids-gcm-network-manager.md
> Added files via upload

- TODO/web-font-loading-patterns.md
> 网络字体加载优化 翻译完成

- TODO/10-things-you-probably-didnt-know-about-javascript-react-and-nodejs-and-graphql-development-at-facebook.md
> 10-things-you-probably-didnt-know... 翻译完成

- TODO/better-node-with-es6-pt-i.md
以阿姆斯特朗加速回旋加速式的速度提交翻译 @antonia0912 
静候校对小伙伴的帮助
issue 见 #300
> 完成 使用ES6写更好的JavaScript part I：广受欢迎新特性

- TODO/the-GCD-handbook.md
> 翻译the-GCD-handbook

- TODO/reducing-jpg-file-size.md
@xcc3641 @galenyuan 翻译完啦，可以来校对了
> 减小 JPG 文件大小 - 翻译完成

- TODO/getting-started-with-jrebel-for-android.md
> 完成 Getting started with JRebel for Android 翻译

- TODO/jquery-3-0-final-released.md
- TODO/no-excuses-it-takes-5-mins-make-that-drawer-visible-under-your-status-bar-2.md
> 怎样在 5 分钟内使 Drawer 在状态栏下可见 翻译

- TODO/jquery-3-0-final-released.md
> jquery 3.0 终于发布了 翻译

- TODO/android-themes-an-in-depth-guide.md
#450 初稿，有劳 @shixinzhang @a-voyager 二位了。
> 深度讲解 Android 主题

- TODO/how-to-build-a-material-design-prototype-using-sketch-and-pixate-part-three.md
原文有些飘= =，自己有些省略了一些作者的俏皮话。校对小伙伴，多帮忙看看，有不对的直接提出哈~
>  A MATERIAL DESIGN PROTOTYPE  完成翻译

- TODO/using-new-google-sheets-api.md
> 如何应用最新版的谷歌表格 API

- TODO/from-a-react-point-of-vue-comparing-reactjs-to-vuejs-for-dynamic-tabular-data.md
> [较为完整的 React.js / Vue.js 的性能比较 Part 1]--翻译完成

- TODO/things-i-wish-i-knew-before-i-wrote-my-first-android-app.md
将“持有“改为“隐式引用”属于纠正翻译错误。其余都是语法问题。
> 改正语法错误和翻译错误

- TODO/build-tic-tac-toe-with-ai-using-swift.md
💥 Ready For Merge💥
RP for #527
> Readiness: Add translation for [Build Tic Tac Toe with AI using Swift]

- TODO/using-zopfli-to-optimize-png-images.md
> 使用zopfli来优化png图片 翻译完成

- TODO/complexion-reduction-a-new-trend-in-mobile-design.md
> 移动应用设计新趋势 提交翻译

- TODO/popovers-on-popovers.md
@sqrthree 翻译完成，这篇文章看似短，内容翻起来很绕口，要辛苦校对者了
> iOS 开发，该如何解决弹窗的设计问题？

- TODO/server-side-web-components-how-and-why.md
> 为什么我们要用网页端组件去构建服务器？该怎么做？

- TODO/empty-state-mobile-app-nice-to-have-essential.md
> 在开发移动应用时你应该考虑的 「Empty State」

- TODO/bridging-existentials-generics-swift-2.md
💥 Ready For Merge💥
PR for #578
> 完成: Swift 2 中为实存类型和泛型搭桥牵线

- TODO/building-ios-apps-with-xamarin-and-visual-studio.md
💥 Ready For Merge💥
PR for #575
> 完成: 用 Xamarin 和 Visual Studio 构建 iOS 应用

- TODO/using-a-core-data-model-in-swift-playgrounds.md
> 在 Swift Playgrounds 中使用 Core Data 模型

- TODO/timer-problems.md
> 安全的计时器设计模式

- TODO/explain-activity-launch-mode-with-examples.md
> Activity 的正确打开方式

- TODO/practical-svg.md
> 嘿，Logo，你应该是这个尺寸的！

- TODO/backend-api-documentation-in-swift.md
💥 Ready For Merge 💥
- PR for #638
> 完成： Swift 中的后端 API 文件

- TODO/designers-problem.md
> 完成：如何根据 OS 平台设计一款手机 APP

- TODO/reactive-generic-segue-with-rxswift.md
第二句的not a fun of using it，有点怀疑是not a fan
> 用RxSwift实现通用的响应式转场

- TODO/writing-better-css-with-currentcolor.md
> [英] 使用'currentColor' 属性写出更好的 CSS 代码 基本翻译完成

- TODO/how-to-test-a-singleton-in-an-android-service-one.md
https://github.com/xitu/gold-miner/issues/777
初稿完成，请校对
> 如何测试 Android 服务里的单例模式（1）? 初稿

- TODO/how-to-test-a-singleton-in-an-android-service-2.md
https://github.com/xitu/gold-miner/issues/778
初稿完成，请校对 # #
> 如何测试 Android 服务里的单例模式（2）? 初稿

- TODO/android-handler-internals.md
Android-handler-internal翻译完毕 @antonia0912 @sqrthree
> 探索Android大杀器——Handler

- TODO/an-introduction-to-the-usernotifications-framework.md
> UserNotifications Framwork 入门介绍

- TODO/Overview-of-JavaScript-ES6-features-a-k-a-ECMAScript-6-and-ES2015.md
> 🎃JavaScript ES6 核心功能一览 初稿完成

- TODO/so-you-want-to-be-a-functional-programmer-part-2.md
- TODO/so-you-want-to-be-a-functional-programmer-part-3.md
> 准备充分了嘛就想学函数式编程？(Part 2) 

- TODO/so-you-want-to-be-a-functional-programmer-part-3.md
> 准备充分了嘛就想学函数式编程？(Part 3)

- TODO/39-open-source-swift-ui-libraries-for-ios-app-development.md
> 给 iOS App 开发者的 39 个开源的 Swift UI 库

- TODO/machine-learning-for-android-developers-with-the-mobile-vision-api-part-1-face-detection.md
-  Pull Request for #841
@sqrthree
> Android 开发者如何通过运动视觉 API 进行机器学习？Part 1 — 人脸检测

- TODO/what-i-learned-from-writing-six-functions-that-all-did-the-same-thing.md
> 在学写了六个功能一样的函数之后，我学到了什么

- TODO/building-android-apps-30-things-that-experience-made-me-learn-the-hard-way.md
-  Pull Request for #879
@sqrthree
> 翻译完成: 构建 Android APP 一定要绕过的 30 个坑

- TODO/progressive-web-apps-with-react-js-part-i-introduction.md
https://github.com/xitu/gold-miner/issues/921
> 翻译渐进式 Web 系列第一篇

- TODO/six-of-the-most-exciting-es6-features-in-node-js-v6-lts.md
翻译完啦，请管理员审核 @sqrthree 辛苦啦~
请各位大神校稿~
> Node.js v6 LTS 的六个 ES6 新特性

- TODO/react-native-android-app-memory-investigation.md
@sqrthree 翻译完成~
翻到最后才发现是韩国人写的。。而且这篇文章其实是教怎么查找内存泄漏的。。
>  React Native Android 应用内存使用探究

- TODO/using-fetch-as-google-for-seo-experiments-with-react-driven-websites.md
-  Pull Request for #918 
@sqrthree
> 使用 “Google 抓取方式” 测试 React 驱动的网站 SEO

- TODO/native-modules-for-react-native-android.md
> React Native Android 的 native 模块

- TODO/python-dynamic-attributes.md
翻译完成，请管理员审核 @sqrthree 
欢迎大神来校对，这篇文章非常短！
> 带你声明 Python 中的可变属性

- TODO/19-things-i-learnt-reading-the-nodejs-docs.md
> 研读 NodeJS 文档，我知道了这 19 件事

- TODO/progressive-web-apps-with-react-js-part-4-site-is-progressively-enhanced.md
先提交 Pull Request。
文章实在太长，时间仓促，后面的半部分翻译的不是很通畅，还需要琢磨。
欢迎大家校对，待周末再仔细 review
> 使用 React.js 的渐进式 Web 应用程序：第 4 部分 - 渐进增强

- TODO/progressive-web-apps-with-react-js-part-3-offline-support-and-network-resilience.md
> [终稿]使用 React.js 的渐进式 Web 应用程序：第 3 部分 - 离线支持和网络恢复能力

- TODO/progressive-web-apps-with-react-js-part-3-offline-support-and-network-resilience.md
> [改格式] 使用 React.js 的渐进式 Web 应用程序：第 3 部分 - 离线支持和网络恢复能力

- TODO/a-dramatic-tour-through-pythons-data-visualization-landscape-including-ggplot-and-altair.md
补充了原 markdown 文件失效的图片链接，并调整了 code block。
> Python 数据可视化概览（涵盖 ggplot 和 Altair）

- TODO/protocol-oriented-programming.md
翻译完了，请管理员审核 @sqrthree 
请大神们来校稿，辛苦啦~
> Swift 面向协议编程，灵丹妙药或是饮鸩止渴？

- TODO/tensorflow-in-a-nutshell-part-one-basics.md
> 简明 TensorFlow 教程 —— 第一部分：基础知识

- TODO/tensorflow-in-a-nutshell-part-three-all-the-models.md
> TensorFlow —  第三部分: 所有的模型

- TODO/python-introspection-with-the-inspect-module.md
翻译完成，请审核~ @sqrthree 
欢迎大神们来校稿，辛苦啦~
> 来写一个 Python 说明文档生成器吧

- TODO/generative-research-ux.md
> 使用强大的调查技巧了解用户的动机

- TODO/effective-java-for-android-cheatsheet.md
> Android 中的 Effective Java(速查表)

- TODO/tensorflow-in-a-nutshell-part-two-hybrid-learning.md
@sqrthree 完成：简明 TensorFlow 教程 —第二部分：混合学习 的翻译
> 简明 TensorFlow 教程 —第二部分：混合学习

- TODO/progressive-web-amps.md
> 渐进增强的 Web AMP

- TODO/getting-started-with-retrofit.md
> 网络请求框架 Retrofit 2 使用详解

- TODO/using-a-function-in-setstate-instead-of-an-object.md
> 在 `setState` 中使用函数替代对象

- TODO/android-data-binding-recyclerview.md
> Android 数据绑定之: RecyclerView 

- TODO/solid-principles-the-definitive-guide.md
@sqrthree 翻译完毕，要麻烦校对者们帮忙指错了。暂时还没有删掉原文。
> SOLID 原则：权威指南

- TODO/the-next-step-for-reactive-android-programming.md
> Android 响应式编程的未来展望

- TODO/the-caching-antipattern.md
@sqrthree 我终于搞定了，I'm sooooooo sorry，根号三大爷请审核~
请大神们来校对啦~
> 为何我抵制使用缓存？

- TODO/rxandroid-tutorial.md
> 翻译完成——RxAndroid Tutorial #1148

- TODO/forms-need-validation.md
> 每一个表单都渴望验证

- TODO/introduction-to-protocol-oriented-programming-in-swift.md
@sqrthree 翻译完成，意译了一小部分，原代码格式都调整了一下。
> Swift 面向协议编程入门 

- TODO/making-magic-with-websockets-and-css3.md
@sqrthree 翻译完成，请管理员审核，辛苦啦~
请大神们来校对，谢谢啦~
> 使用 WebSocket 和 CSS3 创造魔法

- TODO/scrolling-behavior-for-appbars-in-android.md
@sqrthree 基本翻译完毕。很多短语比较抽象，翻译起来有点难度，希望校对者们指错，非常感谢。
> 安卓应用栏的滚动效果

- TODO/how-to-write-a-javascript-package-for-both-node-and-the-browser.md
for issue #1147, first version
> 怎样写一个能同时用于 Node 和浏览器的 JavaScript 包？

- TODO/mosby3-mvi.md
@sqrthree 翻译完毕，文章比较长，难免有错漏，希望校对者指错～
> Model-View-Intent 模式下的响应式应用 － 第一部分 － Model（模型）

- TODO/constraint-layout-hell.md
> ConstraintLayout (这到底是什么)

- TODO/sharing-files-though-intents-are-you-ready-for-nougat.md
> Android Nougat 中通过 Intents 共享文件，你准备好了吗？

- TODO/constraint-layout-concepts-hell-tips-tricks-part-2.md
> Constraint Layout Concepts ( What the hell is this ) (Tips and Tricks) Part 2

- TODO/million-requests-per-second-with-python.md
> 用 Python 实现每秒百万级请求

- TODO/how-google-builds-a-web-framework.md
真没想到 google 用类似 svn 来控制版本
恳请校对
1. 第一次翻译，翻译不对的地方希望能解释一下，学习一下
2. 很多直译不通的地方，意译了，还望检查一下
3. 希望力求信达雅，还望润色
> Google 是如何构建 web 框架的

- TODO/towards-godless-android-development-how-and-why-i-kill-god-objects.md
> 面向无神论安卓开发：如何和为什么要干掉上帝对象

- TODO/redux-4-ways.md
[#1305](https://github.com/xitu/gold-miner/issues/1305)
> 处理 Redux 异步 Action 的 4 种方式

- TODO/a-cartoon-intro-to-webassembly.md
> 看漫画，学 WebAssembly

- TODO/how-to-make-your-react-native-app-respond-gracefully-when-the-keyboard-pops-up.md
How to make your React Native app respond gracefully when the keyboard pops up
> 如何让你的 React Native 应用在键盘弹出时优雅地响应

- TODO/where-is-webassembly-now-and-whats-next.md
> part6-WebAssembly 的现在与未来.md

- TODO/if-i-have-one-month-to-learn-ios-how-would-i-spend-it.md
看来全世界人们都爱 Raywenderlich 。
@sqrthree
> 如果只有一个月入门 iOS：我该如何学习呢？

- TODO/what-makes-webassembly-fast.md
Update what-makes-webassembly-fast
为什么 WebAssembly 执行的更快？
> part5-为什么 WebAssembly 执行的更快？.md

- TODO/animated-intro-rxjs.md
> 看动画，学 RxJS

- TODO/are-the-ux-articles-youre-reading-trying-to-sell-you-something.md
> 你阅读的关于用户体验的文章在试图向你推销什么吗？

- TODO/pull-vs-push-imperative-vs-reactive-reactive-programming-android-rxjava2-hell-part2.md
> 拉模式和推模式，命令式和响应式 – 响应式编程 [Android RxJava2]（这到底是什么）：第二部分

- TODO/life-after-js-learning-2nd-language.md
> remove ads

- TODO/swift-retention-cycle-in-closures-and-delegate.md
> Swift 闭包和代理中的保留周期

- TODO/detect-bots-apache-nginx-logs.md
> 在 Apache & Nginx 日志里检测爬虫机器人

- TODO/using-devtools-tweak-designs-browser.md
翻译完成，请帮忙校对~ 感谢
issue：https://github.com/xitu/gold-miner/issues/1471
@sqrthree
> 使用开发者工具在浏览器中调整设计

- TODO/react-is-slow-react-is-fast.md
> React 的慢与快：优化 React 应用实战

- TODO/modern-javascript-for-ancient-web-developers.md
> 写给“古代” Web 开发者的“现代” JavaScript 指南

- TODO/webpack-bits-getting-the-most-out-of-the-commonschunkplugin.md
[1451](https://github.com/xitu/gold-miner/issues/1451)
> webpack 拾翠：充分利用 CommonsChunkPlugin()

- TODO/war-learning-curve-rx-java-2-java-8-stream-android-rxjava2-hell-part4.md
翻译完成，请安排校对。
为了方便校对，没有修改初始文件的排版，将在校对后视情况修改。
原文口语化较严重，请校对把重点放到语义、概念、排版和错别字上。
> 大战 RxJava2 和 Java8 Stream [ Android RxJava2 ] （这到底是什么） 第四部分

- TODO/why-learn-functional-programming-in-javascript-composing-software.md
@sqrthree 翻译初稿
[issue 1502](https://github.com/xitu/gold-miner/issues/1502)
> 为什么用 JavaScript 学习函数式编程？（软件编写）（第二部分）

- TODO/secure-web-app-http-headers.md
> 如何使用 HTTP Headers 来保护你的 Web 应用

- TODO/a-functional-programmers-introduction-to-javascript-composing-software.md
> 函数式程序员的 JavaScript 简介（软件编写）（第三部分）

- TODO/mastering-swift-essential-details-about-strings.md
> 掌握 Swift 的字符串细节

- TODO/introduction-nginscript.md
issue: https://github.com/xitu/gold-miner/issues/1436 @sqrthree 
初次翻译，请帮忙校对，谢谢！🙏
> nginScript 入门

- TODO/so-whats-this-graphql-thing-i-keep-hearing-about.md
> 我经常听到的 GraphQL 到底是什么？

- TODO/code-comments-the-good-the-bad-and-the-ugly.md
> 代码中添加注释之好坏丑

- TODO/es6-modules-support-lands-in-browsers-is-it-time-to-rethink-bundling.md
> ES6 模块原生支持在浏览器中落地，是时候该重新考虑打包了吗？

- TODO/dialogue-rx-observable-developer-android-rxjava2-hell-part5.md
- TODO/project-need-react.md
> 开发者（也就是我）与 Rx Observable 类的对话 [ Android RxJava2 ] ( 这到底是什么？) 第五部分

- TODO/projects-need-react.md
> 哪些项目需要 React？都需要！

- TODO/the-worlds-fastest-javascript-memoization-library.md
> * 原文地址：[How I wrote the world's fastest JavaScript memoization library](https://community.risingstack.com/the-worlds-fastest-javascript-memoization-library/)
> * 原文作者：[Caio Gondim](https://community.risingstack.com/author/caio/)
> * 译文出自：[掘金翻译计划](https://github.com/xitu/gold-miner)
> * 译者：[薛定谔的猫](https://github.com/Aladdin-ADD)
> * 校对者：
**有一些不确定的地方，我用？？？标注出来了。请大佬们指教! 🙏 ~**
> 翻译：我是如何实现世界上最快的 JavaScript 记忆化的

- TODO/test-driving-away-coupling-in-activities.md
@sqrthree 翻译完成
对应issue：[issue](https://github.com/xitu/gold-miner/issues/1560#issuecomment-298033098)
> 通过测试来解耦Activity

- TODO/familiarity-bias-is-holding-you-back-its-time-to-embrace-arrow-functions.md
> 别让你的偏爱拖了后腿：快拥抱箭头函数吧！

- TODO/how-we-created-bubblepicker-a-colourful-animation-for-android.md
https://github.com/xitu/gold-miner/issues/1628
> 如何创建 BubblePicker – Android 多彩菜单动画

- TODO/workcation-app-part-2-animating-markers-with-mapoverlaylayout.md
通勤路上翻译，可能有不合适的地方，校对费心了。
最近通勤时间比想象的要长的多，如无意外应该可以翻译完整个系列。
@sqrthree
> Workcation App – 第二部分. 有动画的标记和 MapOverlayLayout

- TODO/workcation-app-part-1-fragments-custom-transition.md
初翻完成
@sqrthree 
[issue地址](https://github.com/xitu/gold-miner/issues/1620#issuecomment-299357857)
> Workcation App – 第一部分 . 自定义 Fragment 转场动画

- TODO/make-or-break-with-gradle.md
> Make or break… with Gradle

- TODO/postgres-full-text-search-with-django.md
> Django 基于 Postgres 的全文搜索

- TODO/ios-11-notable-uikit-additions.md
@sqrthree ，翻译完毕
这篇文章的作者方言味太浓了，感觉我学的是假英语，翻译的无比痛苦，跪求大神校对
> iOS 11：UIKit 中重要的新能力

- TODO/love-letter-css.md
[1738](https://github.com/xitu/gold-miner/issues/1738)
> 一封写给 CSS 的情书

- TODO/ios-11-machine-learning-for-everyone.md
- iOS 11: Machine Learning for everyone
- Issue: https://github.com/xitu/gold-miner/issues/1800
- @sqrthree 初稿完成
> iOS 11：机器学习人人有份

- TODO/convincing-the-kotlin-compiler-that-code-is-safe.md
@sqrthree 翻译version1完成 原地址  #1786
> 说服Kotlin编译器代码安全

- TODO/whats-new-in-ios-11.md
> 开发者眼中 iOS 11 都更新了什么？

- TODO/react-redux-optimization.md
@sqrthree 翻译完成 [#1864](https://github.com/xitu/gold-miner/issues/1864)
> Redux 并不慢，只是你使用姿势不对 —— 一份优化指南

- TODO/natural-language-processing-made-easy-using-spacy-in-python.md
> 使用 Python+spaCy 进行简易自然语言处理

- TODO/enhancing-css-layout-floats-flexbox-grid.md
> 渐进增强的 CSS 布局：从浮动到 Flexbox 到 Grid

- TODO/convert-time-series-supervised-learning-problem-python.md
> 如何将时间序列问题用 Python 转换成为监督学习问题

- TODO/generic-data-sources-in-swift.md
> Swift 中的通用数据源

- TODO/contextual-chat-bots-with-tensorflow.md
> 基于 TensorFlow 的上下文聊天机器人

- TODO/all-about-react-router-4.md
> 关于 React Router 4 的一切

- TODO/an-introduction-to-functional-reactive-programming.md
翻译这篇讲 Android 的文章居然帮我理解了前端框架很多概念(捂脸) resolve #1998
@sqrthree
> 函数式响应编程入门指南

- TODO/why-we-desperately-need-women-to-design-ai.md
> 为什么我们渴求女性来设计 AI

- TODO/scaling-node-js-applications.md
- TODO/state-containers-in-swift.md
@sqrthree 终于翻译完了～这个作者太啰嗦了。。
resolve #1971
> 扩展 Node.js 应用

- README.md
> 更新译者数量，增加官方账号等部分。

- TODO/web-fonts-when-you-need-them-when-you-dont.md
> 网络字体：什么时候需要，什么时候不需要

- TODO/making-the-web-more-accessible-with-ai.md
> 使用 AI 为 Web 网页增加无障碍功能

- TODO/taming-great-complexity-mvvm-coordinators-and-rxswift.md
> MVVM, Coordinators 和 RxSwift 的抽丝剥茧

- TODO/securing-cookies-in-go.md
> 在 Go 语言中增强 Cookie 的安全性

- TODO/angular-vs-react-which-is-better-for-web-development.md
> Angular 与 React：谁更适合前端开发

- TODO/a-unified-styling-language.md
Reverts xitu/gold-miner#1778
这篇文章需要重新校对，revert一下。
> Revert "统一样式语言"

- TODO/switching-site-https-shoestring-budget.md
> 低成本将你的网站切换为 HTTPS

- TODO/why-context-value-matters-and-how-to-improve-it.md
> Add Proofreaders

- TODO/using-arkit-with-metal-part-2.md
> 通过 Metal 来使用 ARKit (下)

- TODO/courseras-journey-to-graphql.md
译文翻译完成，resolve #2147 
其实对 GraphQL 不是特别熟，有些地方大概不太对，还请多多指教~
> Coursera 的 GraphQL 之路

- TODO/building-trello-layout-css-grid-flexbox.md
> 使用 CSS 栅格和 Flexbox 打造 Trello 布局

- TODO/managing-css-js-http-2.md
> 在 HTTP/2 的世界里管理 CSS 和 JS

- TODO/the-tiny-keyboard-problem-do-people-complete-forms.md
> 「小键盘」难题：用户在手机上填写表单吗？

- TODO/talk-the-state-of-the-web.md
> 网络现状：性能提升指南

- TODO/post-a-boarding-pass-on-facebook-get-your-account-stolen.md
> 在 Facebook 发一张登机牌，你就有可能被盗号了

- TODO/why-composition-is-harder-with-classes.md
> 为什么在使用了类之后会使得组合变得愈发困难（软件编写）（第九部分）

- TODO/postgres-atomicity.md
> 混乱世界中的稳定：Postgres 如何使事务原子化

- TODO/the-many-faces-of-this-in-javascript.md
> Javascript 中多样的 this

- TODO/designing-websites-for-iphone-x.md
> iPhone X 网页设计

- TODO/performance-metrics-whats-this-all-about.md
> 性能指标都是些什么鬼？

- TODO/recurrent-neural-networks-rnn-part-2-text-classification.md
> RNN 循环神经网络系列 2：文本分类

- TODO/recurrent-neural-networks-rnn-part-1-basic-rnn-char-rnn.md
> RNN 循环神经网络系列 1：基本 RNN 与 CHAR-RNN

- TODO/recurrent-neural-network-rnn-part-4-attentional-interfaces.md
> RNN 循环神经网络系列 4: 注意力机制

- TODO/Under-the-hood-ReactJS.md
> Under-the-hood-ReactJS

- TODO/recurrent-neural-network-rnn-part-5-custom-cells.md
> RNN 循环神经网络系列 5: 自定义单元

- TODO/migrating-mediastyle-notifications-to-support-android-o.md
> 在 Android O 上用到 MediaStyle 的提醒功能

- TODO/migrating-mediastyle-notifications-to-support-android-o.md
developer.android.com --> developer.android.google.cn
译文翻译完成，resolve #<id>
> 把官方文档网站改为 .cn 域名。

- TODO/rebuilding-slack-com.md
> 重建 slack.com：使用 CSS Grid 重新设计，并针对性能和可访问性进行了优化。

- TODO/viewmodels-and-livedata-patterns-antipatterns.md
> ViewModel 和 LiveData：为设计模式打 Call 还是唱反调？

- TODO/how-to-debug-front-end-console.md
> 前端 Console 调试小技巧

- TODO/audio-focus-1.md
> 理解音频焦点（第1/3部分）：常见的音频焦点用例

- TODO/metaprogramming-in-es6-symbols.md
译文翻译完成，resolve #2328 
@leviding 抱歉，最近工作太忙
> 元编程：Symbol，了不起的 Symbol

- TODO/metaprogramming-in-es6-part-2-reflect.md
译文翻译完成，resolve #2327 
@leviding
> ES6 中的元编程：第二部分 —— 反射（Reflect）

- TODO/metaprogramming-in-es6-part-3-proxies.md
> ES6 中的元编程： 第三部分 - 代理（Proxies）

- TODO/how-javascript-works-inside-the-v8-engine-5-tips-on-how-to-write-optimized-code.md
> JavaScript 如何工作：在 V8 引擎里 5 个优化代码的技巧

- TODO/new-in-python-3.7.md
> Python 3.7 的新特性

- TODO/viewmodels-persistence-onsaveinstancestate-restoring-ui-state-and-loaders.md
译文初翻完成，请各路大佬指正。
@leviding 
resolve #2390
> ViewModel：持久化、onSaveInstanceState()、UI 状态恢复和 Loader 

- TODO/how-to-write-high-performance-code-in-golang-using-go-routines.md
译文翻译完成，resolve #2167 
断断续续终于翻译完了，我检讨，积分分给校对者吧
> 如何使用 Golang 中的 Go-Routines 写出高性能的代码

- TODO/what-will-bitcoin-look-like-in-twenty-years-1.md
> 20 年后比特币将会变成什么样 - 第一部分

- TODO/handling-scrolls-with-coordinatorlayout.md
> 用 CoordinatorLayout 处理滚动

- TODO/securing-your-express-app.md
> 为你的网站带上帽子 — 使用 helmet 保护 Express 应用

- TODO/functional-programming-for-android-developers-part-3.md
Android 开发者如何函数式编程 （三）
译文翻译完成，resolve #2452
> Android 开发者如何函数式编程 （三）

- TODO/so-you-want-to-learn-react-js.md
你想学 React.js 吗？
译文翻译完成，resolve #2599
> 你想学 React.js 吗？

- TODO/use-a-render-prop.md
译文翻译完成，resolve #2488
@leviding
> 用 Render props 吧！

- TODO/how-to-cancel-your-promise.md
译文翻译完成，resolve #2601
@leviding
> 如何取消你的 Promise？

- TODO/introducing-turbo-5x-faster-than-yarn-npm-and-runs-natively-in-browser.md
> 介绍 Turbo：比 Yarn 和 NPM 快 5 倍，可以在本地浏览器中运行

- TODO/new-android-injector-with-dagger-2-part-2.md
全新 Android 注入器 : Dagger 2  （二）
译文翻译完成，resolve #2614
> 全新 Android 注入器 : Dagger 2（二）

- TODO/new-android-injector-with-dagger-2-part-1.md
> 全新 Android 注入器 : Dagger 2  （一）

- TODO/the-easy-way-to-turn-a-website-into-a-progressive-web-app.md
> 将网站转换为渐进式 Web 应用程序之简易教程

- TODO/new-android-injector-with-dagger-2-part-3.md
> 全新 Android 注入器 : Dagger 2（三）

- TODO/outsmarting-subscription-challenges.md
> 智对订阅难点：教你如何应对工作中 10 种常见订阅问题

- TODO/ajax-polling-part-2-sagas.md
> 在 Redux 中使用 AJAX 轮询（二）：Saga 篇

- TODO/ajax-polling-in-react-with-redux.md
译文翻译完成，resolve #2800 
第一次参与，请多指教。
> 在 React & Redux 中使用 AJAX 轮询

- TODO/a-look-back-at-the-state-of-javascript-in-2017.md
> 2017 年 JavaScript 发展状况回顾

- TODO/code-splitting-with-parcel-web-app-bundler.md
> 使用 web 应用打包工具 Parcel 实现代码分割

- TODO/top-javascript-libraries-tech-to-learn-in-2018.md
译文翻译完成，resolve #3002
@leviding
> 2018 年要学习的优秀 JavaScript 库与知识

- TODO/introducing-redux-recompose.md
redux-recompose 介绍：优雅的编写 Redux 中的 action 和 reducer
译文翻译完成，resolve #2924
@leviding
> redux-recompose 介绍：优雅的编写 Redux 中的 action 和 reducer

- TODO/a-guide-to-automating-scraping-the-web-with-javascript-chrome-puppeteer-node-js.md
JavaScript 自动化爬虫入门指北（Chrome + Puppeteer + Node JS）：和 Headless Chrome 一起带你装逼带你飞
译文翻译完成，resolve #2926
> JavaScript 自动化爬虫入门指北（Chrome + Puppeteer + Node JS）：和 Headless Chrome 一起带你装逼带你飞

- TODO/how-does-redux-work.md
Redux 的工作原理
译文翻译完成，resolve #2986
> Redux 的工作过程

- TODO/frontend-in-2017-the-important-parts.md
译文翻译完成，resolve #3003 
@leviding 初步 over
> 前端 2017: 举要删芜

- TODO/how-javascript-works-deep-dive-into-websockets-and-http-2-with-sse-how-to-pick-the-right-path.md
> JavaScript 是如何工作的：深入 WebSockets 和使用了 SSE+ 的 HTTP/2，如何在二者当中做出选择

- TODO/all-you-need-to-know-about-parce.md
> 关于 Parcel 你所需要知道的一切：快速的 Web 应用打包工具 🚀

- TODO/troubleshooting-proguard-issues-on-android.md
> ProGuard 在 Android 上的使用姿势

- TODO/understanding-javascripts-engine-with-cartoons.md
> 漫画图解 JavaScript 引擎： let jsCartoons = ‘Awesome’;

- TODO/developers-are-users-too-introduction.md
> 开发者也是用户 - 简介

- TODO/outside-in-development-with-double-loop-tdd.md
> 利用双环 TDD 进行由外向内的开发

- TODO/a-tinder-progressive-web-app-performance-case-study.md
> PWA 实战：Tinder 的性能优化之道

- TODO/front-end-performance-checklist-2018-4.md
> 2018 前端性能优化清单 - 第 4 部分

- TODO/the-future-of-state-management.md
> 状态管理的未来: 在 Apollo Client 中使用 apollo-link-state管理本地数据

- TODO/meet-the-new-dialog-element.md
> 迎接新的 Dialog 元素

- TODO/whats-new-in-vue-devtools-4-0.md
> Vue Devtools 4.0 有哪些新内容

- TODO/front-end-performance-checklist-2018-1.md
2018 前端性能优化清单——第一部分.md
译文翻译完成，resolve #3071
> 2018 前端性能优化清单——第一部分

- TODO/the-constructor-is-dead-long-live-the-constructor.md
> 构造函数已死，构造函数万岁！

- TODO/keep-webpack-fast-a-field-guide-for-better-build-performance.md
> 保持 webpack 快速运行的诀窍：一本提高构建性能的现场指导手册

- TODO/facebook-open-sources-detectron.md
> Facebook 开源了物体检测研究项目 Detectron

- TODO/css-naming-conventions-that-will-save-you-hours-of-debugging.md
>  这些 CSS 命名规范将省下你大把调试时间 

- TODO/front-end-performance-checklist-2018-3.md
> 2018 前端性能优化清单 - 第 3 部分

- TODO/front-end-performance-checklist-2018-1.md
> fix 2018 前端性能优化清单 —— 第一部分 typo

- TODO/js-things-i-never-knew-existed.md
> 我未曾见过的 JS 特性

- TODO/design-your-app-for-decision-making.md
译文翻译完成，resolve #3080
@leviding
> 想帮助用户做决定？你的 APP 可以这样设计！

- TODO/how-modern-web-browsers-accelerate-performance-the-networking-layer.md
> 现代浏览器是如何提升性能的：网络层

- TODO/turning-design-mockups-into-code-with-deep-learning-1.md
> 使用深度学习自动生成HTML代码 - 第 1 部分

- TODO/breakpoints-debugging-like-pro.md
译文翻译完成，resolve #3182 
@leviding
> 断点：像专家一样调试代码

- TODO/webpack-4-beta-try-it-today.md
> 🚀webpack 4 测试版 —— 现在让我们先一睹为快吧!

- TODO/contributing-hugh-lib.md
为 Django Framework 贡献你的力量并没有想象中的那么难
译文翻译完成，resolve #3205
> 为 Django Framework 贡献你的力量并没有想象中的那么难

- TODO/the-complete-guide-to-network-unit-testing-in-swift.md
> swift 网络单元测试完全手册

- TODO/how-to-use-a-model-view-viewmodel-architecture-for-ios.md
不再对 MVVM 感到绝望
译文翻译完成，resolve #3221
> 不再对 MVVM 感到绝望

- TODO/debugging-swift-code-with-lldb.md
译文翻译完成，resolve #3181 
@fanyijihua @leviding @Danny1451
> 用 LLDB 调试 Swift 代码

- TODO/how-to-configure-nginx-for-a-flask-web-application.md
> 为 Flask Web 应用配置 Nginx

- TODO/exploring-es7-decorators.md
译文翻译完成，resolve #3218 
非常抱歉，由于之前的 Pull requests（#3241） ，fork 的仓库被我手残删掉了，导致不能根据校对建议修改文件，所以重开这个 Pull requests
@leviding @ZhiyuanSun @ryouaki
感谢二位的专业建议，已经按照你们的建议修改了
> 探索 ECMAScript 装饰器

- TODO/continuation-summer-vs-winter-observable-dialogue-rx-observable-developer-android-rxjava2-hell-part6.md
> 大话（Summer vs Winter Observable）之我与 Rx Observable[Android RxJava2]（这是什么鬼）第六话

- TODO/v3-1-0-such-perf-wow-many-streams.md
> v3.1.0：大幅性能提升并支持服务端流式渲染

- TODO/a-simple-web-app-in-rust-pt-2b.md
使用 Rust 开发一个简单的 Web 应用，第 2b 部分
译文翻译完成，resolve #3067
> 使用 Rust 开发一个简单的 Web 应用，第 2b 部分

- TODO/the-introduction-of-starspace.md
译文翻译完成，resolve #3159 
@leviding 双译者，另一译者是 @SeanW20 ，积分平分
> Facebook 的 AI 万金油：StarSpace 神经网络模型简介

- TODO/whats-new-in-react-16-3.md
也谈 React 16.3(.0-alpha)
译文翻译完成，resolve #3251
> 也谈 React 16.3(.0-alpha)

- TODO/incrementally-migrate-from-sqlite-to-room.md
> 从 SQLite 逐步迁移到 Room

- TODO/a-simple-web-app-in-rust-pt-3.md
使用 Rust 开发一个简单的 Web 应用，第 3 部分 —— 整合
译文翻译完成，resolve #3068
> 使用 Rust 开发一个简单的 Web 应用，第 3 部分 —— 整合

- TODO/writing-unit-tests-in-a-swift-playground.md
> 在 Swift playground 中编写单元测试

- TODO/how-javascript-works-the-building-blocks-of-web-workers-5-cases-when-you-should-use-them.md
> JavaScript 工作原理：Web Worker 的内部构造以及 5 种你应当使用它的场景

- TODO/using-leanbacks-diffcallback.md
> 使用 leanback 的 DiffCallback：和 DiffUtil 回调之间的区别

- TODO/json-javascript-object-notation.md
译文翻译完成，resolve #3270 
文章与前端关系不大，希望python大佬多多指教
> json — JavaScript 对象表示法

- TODO/creating-your-first-blockchain-with-java-part-2-transactions.md
> 用 Java 创造你的第一个区块链之第二部分 — 交易

- TODO/an-exhaustive-guide-to-writing-dockerfiles-for-node-js-web-apps.md
> 一份为 Node.js 应用准备的 Dockerfile 指南

- TODO/promising-promise-tips.md
> 关于 Promise 的 9 个提示

- TODO/service-workers-the-little-heroes-behind-progressive-web-apps.md
> Service workers：Progressive Web Apps 背后的小英雄

- TODO/flutter-5-reasons-why-you-may-love-it.md
> Flutter — 五个你会爱上它的原因

- TODO/making-svg-icon-libraries-for-react-apps
译文翻译完成，resolve [#3343](https://github.com/xitu/gold-miner/issues/3343)
> 为你的 React 应用制作 SVG 图标库

- TODO/Using-Flutter-in-China.md
> 如何在中国使用 Flutter

- TODO/express-js-and-aws-lambda-a-serverless-love-story.md
> Express.js 与 AWS Lambda  —  一场关于 serverless 的爱情故事

- TODO/develop-your-first-application-with-flutter.md
> 用 Flutter 开发你的第一个应用程序

- TODO/creating-an-html5-game-bot-using-python.md
> 用 Python 做一个 H5 游戏机器人

- TODO/get-ready-a-new-v8-is-coming-node-js-performance-is-changing.md
> 做好准备：新的 V8 即将到来，Node.js 的性能正在改变。

- TODO/developing-games-with-react-redux-and-svg-part-1.md
译文翻译完成，[resolve #3466](https://github.com/xitu/gold-miner/issues/3466)
> 使用 React、Redux、SVG 开发游戏 - Part 1

- TODO/open-sourcing-a-10x-reduction-in-apache-cassandra-tail-latency.md
让 Apache Cassandra 尾部延迟减小 10 倍，已开源
译文翻译完成，resolve #3397
> 让 Apache Cassandra 尾部延迟减小 10 倍（已开源）

- TODO/flutter-for-javascript-developers.md
> 为 JavaScript 程序员准备的 Flutter 指南

- TODO1/userland-api-monitoring-and-code-injection-detection.md
> 用户领域 API 监控和代码注入检测

- TODO1/unidirectional-user-interface-architectures.md
UNIDIRECTIONAL USER INTERFACE ARCHITECTURES
译文翻译完成，resolve #3559
> 单向用户界面架构问题研究

- TODO1/how-to-win-back-subscribers-who-cancel.md
怎样把取消订阅的用户吸引回来
译文翻译完成，resolve #3579
> 怎样把取消订阅的用户吸引回来

- TODO1/1-2-3-9-looking-into-assembly-code-of-coercion.md
> Revert "[1] + [2] - [3] === 9!? 类型转换深入研究"

- TODO1/how-to-not-react-common-anti-patterns-and-gotchas-in-react.md
> How to NOT React：React 中常见的反模式与陷阱

- TODO1/top-react-and-redux-packages-for-faster-development.md
> React & Redux 顶级开发伴侣

- TODO1/ethereumbook-wallets.md
Convert source file from asciidoc to markdown
> Convert source file from asciidoc to markdown

- TODO1/pandas-dtypes.md
> Pandas 数据类型概览

- TODO1/machine-learning-for-diabetes-with-python.md
> 用 Python 编程进行糖尿病相关的机器学习

- TODO1/developing-games-with-react-redux-and-svg-part-2.md
译文翻译完成，resolve [#3539](https://github.com/xitu/gold-miner/issues/3539)
> 使用 React、Redux 和 SVG 开发游戏 - Part 2

- TODO1/python-data-cleaning-numpy-pandas.md
翻译完成
resolve #3597 
well... 非常 easy 及入门的教程，个人感觉不是写给程序员的 🌝
> 使用 NumPy 和 Pandas 进行 Python 式数据清理

- TODO1/node-js-can-http-2-push.md
> Node.js 能进行 HTTP/2 推送啦！

- TODO1/how-fast-is-flutter-i-built-a-stopwatch-app-to-find-out.md
>  Flutter 到底有多快？我开发了秒表应用来弄清楚。

- TODO1/why-you-should-totally-switch-to-kotlin.md
> 为什么你应该开始使用 Kotlin

- TODO1/how-to-debug-front-end-optimising-network-assets.md
> 如何调试前端：优化网络资源

- TODO1/interpreting-predictive-models-with-skater-unboxing-model-opacity.md
> 用 Skater 解读预测模型：打开模型的黑箱

- TODO1/building-type-mode-for-stories-on-ios-and-android.md
> 快拍中 Type Mode 在 iOS 和 Android 上的实现

- TODO1/interesting-ecmascript-2017-proposals.md
> 那些好玩却尚未被 ECMAScript 2017 采纳的提案

- TODO1/introducing-new-android-excellence-apps.md
> 介绍 Google Play 上新的优质 Android 应用与游戏

- TODO1/keyword-arguments-in-python.md
> Python 中的键值（具名）参数：如何使用它们

- TODO1/es-modules-a-cartoon-deep-dive.md
> 漫画深入浅出 ES 模块

- TODO1/how-i-fixed-a-very-old-gil-race-condition-in-python-3-7.md
> 我是如何修复 Python 3.7 中一个非常古老的 GIL 竞态条件 bug 的

- TODO1/how-to-watch-flutter-at-google-i-o-2018.md
如何在 Google I/O 2018 以正确的姿势观看
译文翻译完成，resolve #3751
> 在 Google I/O 2018 观看 Flutter 的正确姿势

- TODO1/how-javascript-works-tracking-changes-in-the-dom-using-mutationobserver.md
> JavaScript 是如何运作的：用 MutationObserver 追踪 DOM 的变化

- TODO1/avoiding-the-async-await-hell.md
> 如何逃离 async/await 地狱

- TODO1/google-i-o-2018-for-android-updated-w-more-detailed-map-navigation-assistant-action.md
> 更为详细的地图、导航和助手功能 —— Google I/O 2018 的 Android 应用更新

- TODO1/manage-different-environments-in-your-swift-project-with-ease.md
> 轻松管理 Swift 项目中的不同环境

- TODO1/windows-insets-fragment-transitions.md
> WindowsInsets 和 Fragment 过渡动画

- TODO1/java-bridge-methods-explained.md
> Java 桥接方法详解

- TODO1/build-it-test-it-deliver-it-complete-ios-guide-on-continuous-delivery-with-fastlane-and-jenkins.md
…uous Delivery with fastlane and Jenkins
译文翻译完成，resolve #3703
> 构建、测试、分发！运用 Fastlane 与 Jenkins，完整的 iOS 持交付指南。

- TODO1/how-to-build-a-delightful-loading-screen-in-5-minutes.md
如何在5分钟之内写出一个不错的loading界面
译文翻译完成，resolve #3801
> 如何在 5 分钟之内写出一个不错的 loading 界面

- TODO1/30-minute-python-web-scraper.md
> 30 分钟 Python 爬虫教程

- TODO1/how-javascript-works-under-the-hood-of-css-and-js-animations-how-to-optimize-their-performance.md
译文翻译完成，resolve #3777 @leviding
> JavaScript 是如何工作的：CSS 和 JS 动画背后的原理 + 如何优化性能

- TODO1/bitcoin-in-bigquery-blockchain-analytics-on-public-data.md
> BigQuery 中的比特币：使用公共数据分析区块链

- TODO1/sending-web-push-notifications-from-node-js.md
> 由 Node.js 发送 Web 推送通知

- TODO1/real-time-human-pose-estimation-in-the-browser-with-tensorflow-js.md
> 在浏览器里使用 TenserFlow.js 实时估计人体姿态

- TODO1/parsing-drugbank-xml-or-any-large-xml-file-in-streaming-mode-in-go.md
> 使用 Go 语言的流模式来解析 DrugBank 的 XML（或者任何大的 XML 文件）

- TODO1/how-javascript-works-a-comparison-with-webassembly-why-in-certain-cases-its-better-to-use-it.md
> JavaScript 是如何工作的：对比 WebAssembly + 为什么在某些场景下它比 JavaScript 更合适

- TODO1/protecting-users-with-tls-by-default-in.md
> 在 Android P 中使用默认的 TLS 来保护你的用户

- TODO1/memory-leaks-in-swift.md
> Swift 中的内存泄漏

- TODO1/what-is-a-python-core-developer-pycon-2018.md
> 原文修正，感谢江水寒

- TODO1/a-simple-guide-to-es6-promises.md
一个简单的 ES6 Promises 指南
译文翻译完成，resolve #3895
> 一个简单的 ES6 Promises 指南

- TODO1/talking-django-async-pycon-2018.md
> modify original subtitle in English

- TODO1/protecting-webview-with-safe-browsing.md
通过安全浏览保护WebView
译文翻译完成，resolve #3881
> 通过安全浏览保护 WebView

- TODO1/the-simple-guide-to-server-side-rendering-react-with-styled-components.md
> 使用 styled-components 的 React 服务器端渲染极简指南

- TODO1/what-are-javascript-generators-and-how-to-use-them.md
> 什么是 JavaScript 生成器？如何使用生成器？

- TODO1/sharing-databases-between-laravel-applications.md
> 在 Laravel 应用程序之间共享数据库

- TODO1/spantastic-text-styling-with-spans.md
@leviding @luochen1992  译文校对完成，之前的仓库不小心被我删了。。。只能从新提交了，resolve #3807
> 使用 Span 来修改文本样式的优质体验

- TODO1/homepod-12-wish-list.md
关于 HomePod WWDC 的愿望清单: 测试版程序、新的语音资源、Echo 等功能
译文翻译完成，resolve #3920
> 关于 HomePod WWDC 的愿望清单: 测试版程序、新的语音资源、Echo 等功能

- TODO1/linear-algebra-for-deep-learning.md
> 深度学习中所需的线性代数知识 —— 发布后有错修改

- TODO1/how-to-optimize-your-app-for-android-go-edition.md
> 如何针对 Android 优化您的应用（Go 版）

- TODO1/what-is-a-python-core-developer-pycon-2018.md
**本文是 PyCon 2018 视频字幕翻译，校对者需要根据视频来进行译文校对：**
* YouTube 视频链接：[Mariatta Wijaya - What is a Python Core Developer? - PyCon 2018](https://www.youtube.com/watch?v=hhj7eb6TrtI)
* 百度云视频链接：https://pan.baidu.com/s/1I-1VaMK6M3nHQFjjiCCD0A
译文翻译完成，resolve #3900
> [字幕翻译] 玛利亚塔·维加亚 — 什么是 Python 核心开发者？— PyCon 2018

- TODO1/a-real-world-comparison-of-front-end-frameworks-with-benchmarks-2018-update.md
> 前端开发框架的实战对比（2018年更新）

- TODO1/understanding-python-bytecode-pycon-2018.md
译文翻译完成，resolve https://github.com/xitu/gold-miner/issues/3897
> [字幕翻译] James Bennett — 理解 Python 字节码 — PyCon 2018

- TODO1/the-beginners-guide-to-contributing-to-a-github-project.md
为 GitHub 项目做出贡献的初学者指南
译文翻译完成，resolve #3994
> 为 GitHub 项目做出贡献的初学者指南

- TODO1/kubernetes-distributed-application.md
Kubernetes 分布式应用部署和人脸识别 app 实例
译文翻译完成，resolve #3970
> Kubernetes 分布式应用部署和人脸识别 app 实例

- TODO1/recommendation-woff-2012-12-13.md
> WOFF文件格式 1.0

- TODO1/react-native-at-airbnb-the-technology.md
> Airbnb 中的 React Native：技术部分

- TODO1/to-yarn-and-back-again-npm.m
译文翻译完成，resolve https://github.com/xitu/gold-miner/issues/3947
> 将项目迁移到 Yarn 然后又迁回到 npm

- TODO1/flutter-for-android-developers-how-to-design-linearlayout-in-flutter.md
> 如何在 Flutter 中设计 LinearLayout？

- TODO1/building-a-custom-slider-in-flutter-with-gesturedetector.md
> 使用 Flutter 的 GestureDetector 构建自定义滑块

- TODO1/sunsetting-react-native.md
> Airbnb 中的 React Native （四）：React Native 退役

- TODO1/oxidizing-source-maps-with-rust-and-webassembly.md
> 论 Rust 和 WebAssembly 对源码地址索引的极限优化

- TODO1/how-to-use-flutter-to-build-an-app-with-bottom-navigation.md
> 如何用 Flutter 来创建一个带有底部导航栏的应用程序

- TODO1/whats-next-for-mobile-at-airbnb.md
> Airbnb 中的 React Native（五）：Airbnb 移动端路在何方？

- TODO1/a-gentle-introduction-to-react-motion.md
> 关于 React Motion 的简要介绍

- TODO1/why-robinhood-uses-airflow.md
> Robinhood 为什么使用 Airflow

- TODO1/making-a-todo-app-with-flutter.md
> 用 Flutter 写一个待办事项应用

- TODO1/boost-your-website-performance-with-phpfastcache.md
> 使用 PhpFastCache 提升网站性能

- TODO1/make-3d-flip-animation-in-flutter.md
> 使用 Flutter 制作 3D 翻转动画

- TODO1/defining-component-apis-in-react.md
> 设计 React 组件 API

- TODO1/practical-flutter-my-personal-6-tips-for-newcomers.md
> Flutter 实用指南：给初学者的 6 个小帖士

- TODO1/python-big-data-airflow-jupyter-notebook-hadoop-3-hive-presto.md
> Python 与大数据：Airflow & Jupyter Notebook with Hadoop 3, Spark & Presto

- TODO1/how-to-rewrite-your-sql-queries-in-pandas-and-more.md
> 如何使用 Pandas 重写你的 SQL 查询以及其他操作

- TODO1/writing-cleaner-view-code-by-overriding-loadview.md
> 重写 loadView() 方法使 Swift 视图代码更加简洁

- TODO1/lets-settle-this-part-one.md
resolve #4267 
@leviding 
@sansanshow 
@geniusq1981
> Solve issue #4267

- TODO1/flutter-challenge-youtube.md
挑战 Flutter 之 YouTube
译文翻译完成，resolve #4264
> 挑战 Flutter 之 YouTube

- TODO1/flutter-challenge-twitter.md
挑战 Flutter 之 Twitter
译文翻译完成，resolve #4254
> 挑战 Flutter 之 Twitter

- TODO1/flutter-deep-dive-gestures.md
译文翻译完成，resolve #4201 
原 PR 见 https://github.com/xitu/gold-miner/pull/4246
> 深入 Flutter 之手势

- TODO1/flutter-challenge-whatsapp.md
Flutter 挑战之 WhatsApp
译文翻译完成，resolve #4263
> Flutter 挑战之 WhatsApp

- TODO1/how-i-used-python-to-find-interesting-people-on-medium.md
我是如何使用 Python 在 Medium 上找到并关注有趣的人
译文翻译完成，resolve #4256
> 我是如何使用 Python 在 Medium 上找到并关注有趣的人

- TODO1/build-a-state-management-system-with-vanilla-javascript.md
使用原生 JavaScript 构建状态管理系统
译文翻译完成，resolve #4253
> 使用原生 JavaScript 构建状态管理系统

- TODO1/implementing-svm-and-kernel-svm-with-pythons-scikit-learn.md
> 用 Scikit-Learn 实现 SVM 和 Kernel SVM

- TODO1/databook-turning-big-data-into-knowledge-with-metadata-at-uber.md
Databook：通过元数据，Uber 将大数据转化为知识
译文翻译完成，resolve #4321
> Databook：通过元数据，Uber 将大数据转化为知识

- TODO1/naive-bayes-classifier-sklearn-python-example-tips.md
> Sklearn 中的朴素贝叶斯分类器

- TODO1/flutter-heroes-and-villains-bringing-balance-to-the-flutterverse.md
Flutter 的 Heroes 和 Villains —— 为 Flutterverse 带来平衡
译文翻译完成，resolve #4239
> Flutter 的 Heroes 和 Villains —— 为 Flutterverse 带来平衡

- TODO1/go-graphql-gateway-microservices.md
> 使用 Go 编写微服务及其 GraphQL 网关

- TODO1/camera-enumeration-on-android.md
Android 的多摄像头支持
译文翻译完成，resolve #4379
> Android 的多摄像头支持

- TODO1/why-you-should-replace-foreach.md
译文翻译完成，resolve #4388 
> 吐槽一下，这篇文章没什么含金量。。。
> 在 JavaScript 中 为什么你应当使用 map 和 filter 来替代 forEach

- TODO1/css-variables-dynamic-app-themes.md
> CSS 变量和 JavaScript 让应用支持动态主题 🎨

- TODO1/whats-coming-up-in-javascript-2018-async-generators-better-regex.md
JavaScript 2018 中即将迎来的新功能：异步生成器及更好的正则表达式
译文翻译完成，resolve #4385
> JavaScript 2018 中即将迎来的新功能：异步生成器及更好的正则表达式

- TODO1/how-to-build-a-simple-chrome-extension-in-vanilla-javascript.md
如何使用原生 JavaScript 构建简单的 Chrome 扩展程序
译文翻译完成，resolve #4395
> 如何使用原生 JavaScript 构建简单的 Chrome 扩展程序

- TODO1/css-variables-dynamic-app-themes.md
- TODO1/this-keyword-call-apply-bind-javascript.md
> this 到底指向什么 — 理解 JavaScript 中的 this、call、apply 和 bind

- TODO1/introducing-the-react-profiler.md
React Profiler 介绍
译文翻译完成，resolve #4447
> React Profiler 介绍

- TODO1/history-of-go-testing.md
> SmartyStreets 的 Go 测试探索之路

- TODO1/the-best-database-as-a-service-solutions-of-2018.md
> 2018 年度最佳数据库即服务解决方案

- TODO1/whats-the-difference-between-dogs-html-and-dogs-html.md
./dogs.html 和 /dogs.html 间有什么区别？
译文翻译完成，resolve #4469
> ./dogs.html 和 /dogs.html 间有什么区别？

- TODO1/if-screen-product-designers-designed-physical-products.md
如果界面产品设计师设计实体产品
译文翻译完成，resolve #4490
> 如果界面产品设计师设计实体产品

- TODO1/implementing-linkedpurchasetoken-correctly-to-prevent-duplicate-subscriptions.md
> 正确实现 linkedPurchaseToken 以避免重复订阅

- TODO1/how-to-conditionally-build-an-object-in-javascript-with-es6.md
> 如何使用 JavaScript ES6 有条件地构造对象

- TODO1/building-a-successful-app-or-game-business-in-southeast-asia.md
> 如何在东南亚拓展您的应用业务

- TODO1/clean-architecture-in-go.md
> Go 语言的整洁架构之道/一个使用 gRPC 的 Go 项目整洁架构例子

- TODO1/three-input-element-properties-that-i-discovered-while-reading-mdn.md
我在阅读 MDN 时发现的 3 个 Input 元素属性
译文翻译完成，resolve #4541
> 我在阅读 MDN 时发现的 3 个 Input 元素属性

- TODO1/adaptive-serving-using-javascript-and-the-network-information-api.md
Change-Id: I6059bfe7e796d906c42e865823c7bb5438a197df
译文翻译完成，resolve #4581
> 使用 JavaScript 和网络信息 API 实现自适应服务

- TODO1/good-practices-for-high-performance-and-scalable-node-js-applications-part-3-3.md
- TODO1/how-apple-beat-swiss-watchmakers-at-their-own-game.md
…de-js-applications-part-3-3
译文翻译完成，resolve #4553
> 构建高性能和可扩展性 Node.js 应用的最佳实践 [第 3/3 部分]

- TODO1/introduction-source-maps.md
> 源代码映射（Source Map）简介

- TODO1/a-web-application-completely-in-rust.md
> Rust 开发完整的 Web 应用程序

- TODO1/shine-a-light-on-javascript-performance-with-lighthouse-1opf.md
Change-Id: I3c363919365d20ca64785d7fb0a74f1ae30a2531
译文翻译完成，resolve #4648
> 通过 Lighthouse 了解 JavaScript 性能
